<linked-list>
    <#list acList as object>
        <DeviceDefine>
            <deviceId>${object.deviceId}</deviceId>
            <iSensorDefines>
                <SensorDefine>
                    <name>CRV.OutAir.Temperature.Setting</name>
                    <registerIndex>0</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.OutAir.AvgTemperature</name>
                    <registerIndex>1</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Humidity.Setting</name>
                    <registerIndex>2</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Humidity.Ratio</name>
                    <registerIndex>3</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Out.Temperature.1</name>
                    <registerIndex>4</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Out.Temperature.2</name>
                    <registerIndex>5</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.ReturnAir.Temperature</name>
                    <registerIndex>6</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AirFlow.Temperature</name>
                    <registerIndex>7</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.ExhaustTemperature</name>
                    <registerIndex>8</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.SuctionTemperature</name>
                    <registerIndex>9</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.ReturnAir.Humidity</name>
                    <registerIndex>10</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Exhaust.Presure</name>
                    <registerIndex>11</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Suction.Presure</name>
                    <registerIndex>12</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.OutAir.Temperature.Correcting.1</name>
                    <registerIndex>13</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.OutAir.Temperature.Correcting.2</name>
                    <registerIndex>14</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.ReturnAir.Temperature.Correcting</name>
                    <registerIndex>15</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AirFlow.Temperature.Correcting</name>
                    <registerIndex>16</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.ExhaustTemperature.Correcting</name>
                    <registerIndex>17</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Suction.Presure.Correcting</name>
                    <registerIndex>18</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.ReturnAir.Humidity.Correcting</name>
                    <registerIndex>19</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Exhaust.Presure.Correcting</name>
                    <registerIndex>20</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Suction.Presure.Correcting</name>
                    <registerIndex>21</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Monitor.BaudRate</name>
                    <registerIndex>22</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Monitor.Addr</name>
                    <registerIndex>23</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.A.Phrase.Voltage</name>
                    <registerIndex>24</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.B.Phrase.Voltage</name>
                    <registerIndex>25</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.C.Phrase.Voltage</name>
                    <registerIndex>26</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.PowerFrequency</name>
                    <registerIndex>27</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Compressor.MinOperationTime</name>
                    <registerIndex>28</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Compressor.MinStopTime</name>
                    <registerIndex>29</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Fan.StartDelay</name>
                    <registerIndex>30</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Fan.StopDelay</name>
                    <registerIndex>31</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Suction.Evaporation.Temperature</name>
                    <registerIndex>32</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Exhaust.Condensation.Temperature</name>
                    <registerIndex>33</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Suction.Superheat.Temperature</name>
                    <registerIndex>34</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Exhaust.Superheat.Temperature</name>
                    <registerIndex>35</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Theoretical.OutAir.Humidity</name>
                    <registerIndex>36</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Current.OutAir.Humidity</name>
                    <registerIndex>37</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.DialCode.Value</name>
                    <registerIndex>38</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertState.Num</name>
                    <registerIndex>39</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertState.History.Num</name>
                    <registerIndex>40</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Compressor.StartStop.Num</name>
                    <registerIndex>41</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.WaterPump.StartStop.Num</name>
                    <registerIndex>42</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Fan.StartStop.Num</name>
                    <registerIndex>43</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.ElectricHeating.StartStop.Num</name>
                    <registerIndex>44</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Humidifier.StartStop.Num</name>
                    <registerIndex>45</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Compressor.Operation.HourRecord</name>
                    <registerIndex>46</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.WaterPump.Operation.HourRecord</name>
                    <registerIndex>47</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Fan.Operation.HourRecord</name>
                    <registerIndex>48</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.ElectricHeating.Operation.HourRecord</name>
                    <registerIndex>49</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Humidifier.Operation.HourRecord</name>
                    <registerIndex>50</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_51</commandName>
                    <divider>1</divider>
                </SensorDefine>

                <SensorDefine>
                    <name>CRV.AlertAttr.HighPresure</name>
                    <registerIndex>64</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.LowPresure</name>
                    <registerIndex>65</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.HighPresure.Abnormal</name>
                    <registerIndex>66</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Exhaust.Tempareture.Over</name>
                    <registerIndex>67</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Exhaust.Superheat.Less</name>
                    <registerIndex>68</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.ReturnAir.Tempareture.Over</name>
                    <registerIndex>69</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.OutAir.Tempareture.Less</name>
                    <registerIndex>70</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.OutAir.Tempareture.Over</name>
                    <registerIndex>71</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.ReturnAir.Humidity.Over</name>
                    <registerIndex>72</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.ReturnAir.Humidity.Less</name>
                    <registerIndex>73</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.HighPresure.Lock</name>
                    <registerIndex>74</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.LowPresure.Lock</name>
                    <registerIndex>75</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Exhaust.Tempareture.Over.Lock</name>
                    <registerIndex>76</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Exhaust.Superheat.Less.Lock</name>
                    <registerIndex>77</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Power.Loss</name>
                    <registerIndex>78</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Power.Voltage.Over</name>
                    <registerIndex>79</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Power.Voltage.Less</name>
                    <registerIndex>80</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Power.Lack.Phrase</name>
                    <registerIndex>81</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Floor.Overflow</name>
                    <registerIndex>82</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.WaterLevel.Over</name>
                    <registerIndex>83</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.FilterClog</name>
                    <registerIndex>84</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Filter.Maintenance</name>
                    <registerIndex>85</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.AirFlow.Loss</name>
                    <registerIndex>86</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Sensor.LowPresure.Lock</name>
                    <registerIndex>87</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.RemoteShutdown</name>
                    <registerIndex>88</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.GroupControl.HostMachine.Loss</name>
                    <registerIndex>89</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.GroupControl.ClusterMachine.Loss</name>
                    <registerIndex>90</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Sensor.ReturnAir.Temperature</name>
                    <registerIndex>91</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Sensor.ReturnAir.Humidity</name>
                    <registerIndex>92</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Sensor.AirFlow.TemperatureDiff</name>
                    <registerIndex>93</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Sensor.OutAir.Temperature</name>
                    <registerIndex>94</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Sensor.Remote.Temperature</name>
                    <registerIndex>95</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertAttr.Sensor.HighPresure</name>
                    <registerIndex>96</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.MainStandby.Delay</name>
                    <registerIndex>97</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.FirstOperatingMachineGroup</name>
                    <registerIndex>98</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.HeatingFunction</name>
                    <registerIndex>99</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.RemoteTemperature.Sensor.Num</name>
                    <registerIndex>100</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.CondensatePump</name>
                    <registerIndex>101</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.GroupControl.Mode</name>
                    <registerIndex>102</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.MachineGroup.Addr</name>
                    <registerIndex>103</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.MachineGroup.Num</name>
                    <registerIndex>104</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.StandBy.Num</name>
                    <registerIndex>105</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Rotation.Num</name>
                    <registerIndex>106</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Rotation.Time</name>
                    <registerIndex>107</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Rotation.Cycle</name>
                    <registerIndex>108</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Temperature.DeadZone</name>
                    <registerIndex>109</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Humidity.DeadZone</name>
                    <registerIndex>110</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.RemoteTemperature.Setting</name>
                    <registerIndex>111</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.ReturnAir.Temperature.Setting</name>
                    <registerIndex>112</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.CompressorCapacity.ActualValue</name>
                    <registerIndex>113</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.CompressorCapacity.OutputValue</name>
                    <registerIndex>114</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_64_51</commandName>
                    <divider>1</divider>
                </SensorDefine>

                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.1</name>
                    <registerIndex>130</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.2</name>
                    <registerIndex>131</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.3</name>
                    <registerIndex>132</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.4</name>
                    <registerIndex>133</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.5</name>
                    <registerIndex>134</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.6</name>
                    <registerIndex>135</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.7</name>
                    <registerIndex>136</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.8</name>
                    <registerIndex>137</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.9</name>
                    <registerIndex>138</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.10</name>
                    <registerIndex>139</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.AvgTemperature</name>
                    <registerIndex>140</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertValue.OutAir.Temperature.Over</name>
                    <registerIndex>141</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertValue.OutAir.Temperature.Less</name>
                    <registerIndex>142</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertValue.ReturnAir.Temperature.Over</name>
                    <registerIndex>143</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertValue.ReturnAir.Humidity.Over</name>
                    <registerIndex>144</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertValue.ReturnAir.Humidity.Less</name>
                    <registerIndex>145</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertValue.AirFlow.TemperatureDiff.Loss</name>
                    <registerIndex>146</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Compressor.Control.Mode</name>
                    <registerIndex>147</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Fan.Control.Mode</name>
                    <registerIndex>148</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_130_19</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.1.Correcting</name>
                    <registerIndex>218</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.2.Correcting</name>
                    <registerIndex>219</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.3.Correcting</name>
                    <registerIndex>220</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.4.Correcting</name>
                    <registerIndex>221</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.5.Correcting</name>
                    <registerIndex>222</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.6.Correcting</name>
                    <registerIndex>223</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.7.Correcting</name>
                    <registerIndex>224</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.8.Correcting</name>
                    <registerIndex>225</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.9.Correcting</name>
                    <registerIndex>226</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Remote.WarmSensation.10.Correcting</name>
                    <registerIndex>227</registerIndex>
                    <scale>1</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>10</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Fan.Fault.ProcessingMode</name>
                    <registerIndex>228</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertValue.Power.Over</name>
                    <registerIndex>229</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.AlertValue.Power.Less</name>
                    <registerIndex>230</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_218_13</commandName>
                    <divider>1</divider>
                </SensorDefine>

                <SensorDefine>
                    <name>CRV.SwitchState.Alert.HighPresure</name>
                    <registerIndex>0</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.SwitchState.Alert.HighWaterLevel</name>
                    <registerIndex>1</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.SwitchState.Alert.FloorOverflow</name>
                    <registerIndex>2</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.SwitchState.Alert.ElectricHeatingFault</name>
                    <registerIndex>3</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.SwitchState.Alert.FilterClog</name>
                    <registerIndex>4</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.SwitchState.Alert.HumidifierFault</name>
                    <registerIndex>5</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.SwitchState.WaterLevel</name>
                    <registerIndex>6</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.SwitchState.Remote</name>
                    <registerIndex>7</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.PumpOutPut</name>
                    <registerIndex>12</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.CompressorOutput</name>
                    <registerIndex>13</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.ElectricHeatingOutput</name>
                    <registerIndex>14</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.FanOutput</name>
                    <registerIndex>15</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.HumidifierOutput</name>
                    <registerIndex>16</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.CommonAlertOutput</name>
                    <registerIndex>17</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.LiquidSolenoidValueOutput</name>
                    <registerIndex>19</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.HighPressure</name>
                    <registerIndex>24</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.LowPressure</name>
                    <registerIndex>25</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.HighPressure.Abnormal</name>
                    <registerIndex>26</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Exhaust.Temperature.Over</name>
                    <registerIndex>27</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Exhaust.Superheat.Less</name>
                    <registerIndex>28</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.ReturnAir.Temperature.Over</name>
                    <registerIndex>29</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.OutAir.Temperature.Less</name>
                    <registerIndex>30</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.OutAir.Temperature.Over</name>
                    <registerIndex>31</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.ReturnAir.Humidity.Over</name>
                    <registerIndex>32</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.ReturnAir.Humidity.Less</name>
                    <registerIndex>33</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.HighPresureLock</name>
                    <registerIndex>34</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.LowPresureLock</name>
                    <registerIndex>35</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Exhaust.Temperature.Over.Lock</name>
                    <registerIndex>36</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Exhaust.Superheat.Less.Lock</name>
                    <registerIndex>37</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Power.Loss</name>
                    <registerIndex>38</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Power.Voltage.Over</name>
                    <registerIndex>39</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Power.Voltage.Less</name>
                    <registerIndex>40</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Power.Phase.Miss</name>
                    <registerIndex>41</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.FloorOverflow</name>
                    <registerIndex>42</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.HighWaterLevel</name>
                    <registerIndex>43</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.FilterClog</name>
                    <registerIndex>44</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Filter.Maintenance</name>
                    <registerIndex>45</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.AirFlow.Loss</name>
                    <registerIndex>46</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.LowPressure.Lock</name>
                    <registerIndex>47</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.RemoteShutdown</name>
                    <registerIndex>48</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.GroupControl.HostMachine.Loss</name>
                    <registerIndex>49</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.GroupControl.ClusterMachine.Loss</name>
                    <registerIndex>50</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.ReturnAir.Temperature</name>
                    <registerIndex>51</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.ReturnAir.Humidity</name>
                    <registerIndex>52</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.AirFlow.TemperatureDiff</name>
                    <registerIndex>53</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.OutAir.Temperature</name>
                    <registerIndex>54</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.Remote.Temperature</name>
                    <registerIndex>55</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.HighPresure</name>
                    <registerIndex>56</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Manual.Clear.StartStop.Record</name>
                    <registerIndex>57</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Manual.Clear.HistoryAlert</name>
                    <registerIndex>58</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Manual.Operation.Allow</name>
                    <registerIndex>59</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Restore.FacotrySettings</name>
                    <registerIndex>60</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.Vacuum</name>
                    <registerIndex>61</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Enable.Humidification</name>
                    <registerIndex>62</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Enable.Dehumidification</name>
                    <registerIndex>63</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Clear.HighPressure.Abnormal</name>
                    <registerIndex>64</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Release.DehumidificationLock</name>
                    <registerIndex>65</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Enable.MonitorShutdown</name>
                    <registerIndex>66</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.SoftShutdown</name>
                    <registerIndex>67</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.FlagBit.NewAlert</name>
                    <registerIndex>68</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.FlagBit.PanelShutdown</name>
                    <registerIndex>69</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.FlagBit.MonitorShutdown</name>
                    <registerIndex>70</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.FlagBit.RemoteShutdown</name>
                    <registerIndex>71</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Filter.Maintenance</name>
                    <registerIndex>72</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.Fan1</name>
                    <registerIndex>73</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.Fan2</name>
                    <registerIndex>74</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.Fan3</name>
                    <registerIndex>75</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.Fan4</name>
                    <registerIndex>76</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Backup</name>
                    <registerIndex>77</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.RemoteSwtich.InputPolarity</name>
                    <registerIndex>78</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.State.CommonAlert.InputPolarity</name>
                    <registerIndex>79</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Switch.Change</name>
                    <registerIndex>80</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.FlagBit.Refrigeration</name>
                    <registerIndex>81</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.FlagBit.Heating</name>
                    <registerIndex>82</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.FlagBit.Humidification</name>
                    <registerIndex>83</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.FlagBit.Dehumidification</name>
                    <registerIndex>84</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.ElectricHeating.Fault</name>
                    <registerIndex>85</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.ExhaustTemperature</name>
                    <registerIndex>86</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Fan.Power.Fault</name>
                    <registerIndex>87</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.EEV.Communication</name>
                    <registerIndex>88</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.NotSelectRefrigerant</name>
                    <registerIndex>89</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Refrigerant.Insufficient</name>
                    <registerIndex>90</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.SuctionTemperature</name>
                    <registerIndex>91</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Sensor.LowPressure.Fault</name>
                    <registerIndex>92</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Compressor.DriveCommunication</name>
                    <registerIndex>93</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Compressor.Drive</name>
                    <registerIndex>94</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Compressor.Radiator.Over</name>
                    <registerIndex>95</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Compressor.OverCurrent.Protection</name>
                    <registerIndex>96</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Compressor.Phase.Miss.Protection</name>
                    <registerIndex>97</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Compressor.BusVoltage.Abnormal</name>
                    <registerIndex>98</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Alert.Humidifier.Fault</name>
                    <registerIndex>99</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
                <SensorDefine>
                    <name>CRV.Enable.ServiceInfoRemind</name>
                    <registerIndex>100</registerIndex>
                    <scale>0</scale>
                    <isMean>false</isMean>
                    <commandName>Modbus_${object.index}_CRV_AI_0_101</commandName>
                    <divider>1</divider>
                </SensorDefine>
            </iSensorDefines>
        </DeviceDefine>
    </#list>
</linked-list>