<?xml version="1.0" encoding="UTF-8"?>

<linked-list> 
  <ModbusRequest> 
    <name>pdc_q0_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>4</length>  
    <registerNumber>0</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q1_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>70</length>  
    <registerNumber>4</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q2_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>70</length>  
    <registerNumber>74</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q3_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>144</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q4_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>252</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q5_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>360</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q6_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>468</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q7_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>576</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q8_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>684</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q9_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>792</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q10_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>900</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q11_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>1008</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q12_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>108</length>  
    <registerNumber>1116</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q13_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>72</length>  
    <registerNumber>1224</registerNumber> 
  </ModbusRequest>  
  <ModbusRequest> 
    <name>pdc_q14_${deviceId}_A1</name>
    <commandType>3</commandType>  
    <destinationHost>${ip}</destinationHost>
    <port>${port}</port>
    <busId>${busId}</busId>
    <length>101</length>  
    <registerNumber>4096</registerNumber> 
  </ModbusRequest> 
</linked-list>
