<linked-list>
<#list amsAcList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <CommonDefine>
                <name>CRAC.Indoor.Temperature</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>0</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>CRAC.Indoor.Humidity</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>4</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>CRAC.A.Voltage</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>8</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>CRAC.B.Voltage</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>12</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>CRAC.C.Voltage</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>16</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>Humidifier.Current</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>20</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>Power.frequency</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>24</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>Temperature.1</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>28</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>Temperature.2</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>32</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>Temperature.3</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>36</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>Temperature.4</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>40</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>Analog.Quantity.1</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>44</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>Analog.Quantity.2</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>48</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>Analog.Quantity.3</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>52</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>Analog.Quantity.4</name>
                <commandName>cmd_crac_${object.index}_d1_60_42</commandName>
                <index>56</index>
                <length>4</length>
                <divider>10</divider>
                <isMean>false</isMean>
                <precision>2</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>

            <!--高压开关1-->
            <CommonDefine>
                <name>HighPressure.Switch1.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>0</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--高压开关2-->
            <CommonDefine>
                <name>HighPressure.Switch2.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>2</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--低压开关1-->
            <CommonDefine>
                <name>LowPressure.Switch1.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>4</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--低压开关2-->
            <CommonDefine>
                <name>LowPressure.Switch2.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>6</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--排气温度开关1-->
            <CommonDefine>
                <name>Exhausted.Air.Temperature1.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>8</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--排气温度开关2-->
            <CommonDefine>
                <name>Exhausted.Air.Temperature2.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>10</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>
            <!--过滤网开关-->
            <CommonDefine>
                <name>FilterNet.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>12</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>
            <!--地板溢水开关-->
            <CommonDefine>
                <name>WaterFloor.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>14</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--风机故障开关-->
            <CommonDefine>
                <name>FanException.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>16</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--气流不足开关-->
            <CommonDefine>
                <name>AirFloorNotEnough.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>22</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--自定义开关1-->
            <CommonDefine>
                <name>Custom1.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>24</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--自定义开关2-->
            <CommonDefine>
                <name>Custom2.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>26</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--自定义开关3-->
            <CommonDefine>
                <name>Custom3.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>28</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>


            <!--自定义开关4-->
            <CommonDefine>
                <name>Custom4.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>30</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--CM+水位探头-->
            <CommonDefine>
                <name>CMAndWaterBit.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>32</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>
            <!--远程关机-->
            <CommonDefine>
                <name>RemoteShutDown</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>34</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--加湿器告警-->
            <CommonDefine>
                <name>Humidifier.Alert</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>36</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--烟感输入-->
            <CommonDefine>
                <name>Smoke.Input</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>38</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--电加热告警输入-->
            <CommonDefine>
                <name>Electric.Heating.Input.Alert</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>40</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--红外加湿高水位-->
            <CommonDefine>
                <name>InfraredRay.Humidifier.HighWaterBit</name>
                <commandName>cmd_crac_${object.index}_d1_60_43</commandName>
                <index>42</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--空调开关机状态-->
            <CommonDefine>
                <name>CRAC.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>0</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--风机输出开关状态-->
            <CommonDefine>
                <name>CRAC.Module.1.InnerBlower.1.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>2</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--加湿机输出开关状态-->
            <CommonDefine>
                <name>Humidifier.OutPut.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>4</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--压缩机1输出开关状态-->
            <CommonDefine>
                <name>CRAC.Module.1.Compressor.1.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>6</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--压缩机2输出开关状态-->
            <CommonDefine>
                <name>CRAC.Module.1.Compressor.2.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>8</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--加热1输出开关状态-->
            <CommonDefine>
                <name>CRAC.Module.1.Heater.1.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>10</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--加热2输出开关状态-->
            <CommonDefine>
                <name>CRAC.Module.1.Heater.2.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>12</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--公共报警输出开关状态-->
            <CommonDefine>
                <name>Public.Alarm.OutPut.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>14</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--液路旁通1输出开关状态-->
            <CommonDefine>
                <name>liquid1.ByPass.OutPut.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>16</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--液路旁通2输出开关状态-->
            <CommonDefine>
                <name>liquid2.ByPass.OutPut.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>18</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--注水输出开关状态-->
            <CommonDefine>
                <name>Injected.Water.OutPut.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>20</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--除湿输出开关状态-->
            <CommonDefine>
                <name>Dehumidification.OutPut.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>22</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--备用输出开关状态-->
            <CommonDefine>
                <name>StandBy.OutPut.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>24</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--压缩机1反相输出开关状态-->
            <CommonDefine>
                <name>Compressor1.Reversed.OutPut.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>26</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--压缩机2反相输出开关状态-->
            <CommonDefine>
                <name>Compressor2.Reversed.OutPut.Switch.State</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>28</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--制冷状态-->
            <CommonDefine>
                <name>CRAC.Module.1.MakeCold.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>30</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--加热状态-->
            <CommonDefine>
                <name>CRAC.Module.1.Heating.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>32</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--除湿状态-->
            <CommonDefine>
                <name>CRAC.Module.1.DeHumidity.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>34</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--加湿状态-->
            <CommonDefine>
                <name>CRAC.Module.1.Humidify.RunState</name>
                <commandName>cmd_crac_${object.index}_d1_60_82</commandName>
                <index>36</index>
                <length>2</length>
                <divider>1</divider>
                <precision>1</precision>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <hexCalToInt></hexCalToInt>
                </calcList>
            </CommonDefine>

            <!--空调运行模式 （
            0：单机；1：群控0模式；2：群控1模式；3：群控2模式，4：群控3模式
            -->
            <SwitchSensorDefine>
                <name>CRAC.Running.Type</name>
                <registerIndex>0</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>CRAC.GroupControl.0.Type</name>
                <registerIndex>0</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>CRAC.GroupControl.1.Type</name>
                <registerIndex>0</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>CRAC.GroupControl.2.Type</name>
                <registerIndex>0</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>3</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>CRAC.GroupControl.3.Type</name>
                <registerIndex>0</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>4</routeIndex>
            </SwitchSensorDefine>

            <!--高压1告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Alert.HighVoltage1</name>
                <registerIndex>2</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>

            <!--高压2告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Alert.HighVoltage2</name>
                <registerIndex>2</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>


            <!--低压1告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Alert.LowVoltage1</name>
                <registerIndex>2</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>3</routeIndex>
            </SwitchSensorDefine>

            <!--低压2告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Alert.LowVoltage2</name>
                <registerIndex>2</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>4</routeIndex>
            </SwitchSensorDefine>


            <!--告警_排气温度1 -->
            <SwitchSensorDefine>
                <name>CRAC.Alert.Exhaust.Temperature1</name>
                <registerIndex>2</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>5</routeIndex>
            </SwitchSensorDefine>

            <!--告警_排气温度2 -->
            <SwitchSensorDefine>
                <name>CRAC.Alert.Exhaust.Temperature2</name>
                <registerIndex>2</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>6</routeIndex>
            </SwitchSensorDefine>

            <!--告警_盘管冻结1 -->
            <SwitchSensorDefine>
                <name>CRAC.Alert.Coiler1</name>
                <registerIndex>2</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>7</routeIndex>
            </SwitchSensorDefine>

            <!--告警_盘管冻结2 -->
            <SwitchSensorDefine>
                <name>CRAC.Alert.Coiler2</name>
                <registerIndex>4</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>

            <!--风机1过载告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Module.1.Alarm.InnerBlower.1.Overload</name>
                <registerIndex>4</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <!--风机2过载告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Module.1.Alarm.InnerBlower.2.Overload</name>
                <registerIndex>4</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <!--风机3过载告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Module.1.Alarm.InnerBlower.2.Overload</name>
                <registerIndex>4</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>3</routeIndex>
            </SwitchSensorDefine>
            <!--过滤网阻塞告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Module.1.Alarm.Filter.Fault</name>
                <registerIndex>4</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <!--烟感告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Alarm.Smoke</name>
                <registerIndex>6</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <!--压缩机1运行超时告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Module.1.Alarm.Compressor.1.Overload</name>
                <registerIndex>6</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>6</routeIndex>
            </SwitchSensorDefine>
            <!--压缩机2运行超时告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Module.1.Alarm.Overload.2.Overload</name>
                <registerIndex>6</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>7</routeIndex>
            </SwitchSensorDefine>
            <!--加热器1运行超时告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Module.1.Alarm.Heater.1.Protect</name>
                <registerIndex>7</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <!--加热器2运行超时告警 -->
            <SwitchSensorDefine>
                <name>CRAC.Module.1.Alarm.Heater.2.Protect</name>
                <registerIndex>7</registerIndex>
                <commandName>cmd_crac_${object.index}_d1_60_85</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>

        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
