<linked-list>
<#list acrelList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <CommonDefine>
                <name>ELM.DPT</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>73</index>
                <length>1</length>
                <precision>2</precision>
                <divider>1</divider>
                <isMean>false</isMean>
                <calcList>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.DCT</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>74</index>
                <length>1</length>
                <precision>2</precision>
                <divider>1</divider>
                <isMean>false</isMean>
                <calcList>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.DPQ</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>75</index>
                <length>2</length>
                <precision>2</precision>
                <divider>1</divider>
                <isMean>false</isMean>
                <calcList>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>ELM.A.Voltage</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>77</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.B.Voltage</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>79</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.C.Voltage</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>81</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>ELM.LineVoltage.AB</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>83</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.LineVoltage.BC</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>85</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.LineVoltage.CA</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>87</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>ELM.A.Current</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>89</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.B.Current</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>91</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.C.Current</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>93</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.A.ActivePower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>95</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.B.ActivePower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>97</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.C.ActivePower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>99</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.ActivePower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>101</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.A.ReactivePower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>103</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.B.ReactivePower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>105</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.C.ReactivePower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>107</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.ReactivePower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>109</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.A.PowerFactor</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>111</index>
                <length>2</length>
                <precision>2</precision>
                <divider>1000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.B.PowerFactor</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>113</index>
                <length>2</length>
                <precision>2</precision>
                <divider>1000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.C.PowerFactor</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>115</index>
                <length>2</length>
                <precision>2</precision>
                <divider>1000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.PowerFactor</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>117</index>
                <length>2</length>
                <precision>2</precision>
                <divider>1000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>ELM.A.ApparentPower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>119</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.B.ApparentPower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>121</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.C.ApparentPower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>123</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.ApparentPower</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>125</index>
                <length>2</length>
                <precision>2</precision>
                <divider>10000000</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.Frequency</name>
                <commandName>cmd_acrel_d1_mdbs_AI_${object.index}</commandName>
                <index>127</index>
                <length>2</length>
                <precision>2</precision>
                <divider>100</divider>
                <isMean>false</isMean>
                <calcList>
                    <uint16Calc>
                        <highHead>true</highHead>
                    </uint16Calc>
                </calcList>
            </CommonDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
