<linked-list>
<#list dlyList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <ComputeSensorDefine>
                <name>ELM.A.Voltage</name>
                <highPropertyDefines>
                    <name>ELM.A.Voltage_h</name>
                    <registerIndex>6216</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.A.Voltage_l</name>
                    <registerIndex>6217</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.B.Voltage</name>
                <highPropertyDefines>
                    <name>ELM.B.Voltage_h</name>
                    <registerIndex>6218</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.B.Voltage_l</name>
                    <registerIndex>6219</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.C.Voltage</name>
                <highPropertyDefines>
                    <name>ELM.C.Voltage_h</name>
                    <registerIndex>6220</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.C.Voltage_l</name>
                    <registerIndex>6221</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.LineVoltage.AB</name>
                <highPropertyDefines>
                    <name>ELM.LineVoltage_AB_h</name>
                    <registerIndex>6224</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.LineVoltage_AB_l</name>
                    <registerIndex>6225</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.LineVoltage.BC</name>
                <highPropertyDefines>
                    <name>ELM.LineVoltage_BC_h</name>
                    <registerIndex>6226</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.LineVoltage_BC_l</name>
                    <registerIndex>6227</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.LineVoltage.CA</name>
                <highPropertyDefines>
                    <name>ELM.LineVoltage_CA_h</name>
                    <registerIndex>6228</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.LineVoltage_CA_l</name>
                    <registerIndex>6229</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>

            <ComputeSensorDefine>
                <name>ELM.A.Current</name>
                <highPropertyDefines>
                    <name>ELM.A.Current_h</name>
                    <registerIndex>6232</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>1000</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.A.Current_l</name>
                    <registerIndex>6233</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>1000</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.B.Current</name>
                <highPropertyDefines>
                    <name>ELM.B.Current_h</name>
                    <registerIndex>6234</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>1000</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.B.Current_l</name>
                    <registerIndex>6235</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>1000</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.C.Current</name>
                <highPropertyDefines>
                    <name>ELM.C.Current_h</name>
                    <registerIndex>6236</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>1000</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.C.Current_l</name>
                    <registerIndex>6237</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>1000</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>

            <SensorDefine>
                <name>ELM.A.PowerFactor</name>
                <registerIndex>6276</registerIndex>
                <scale>3</scale>
                <isMean>true</isMean>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.PowerFactor</name>
                <registerIndex>6277</registerIndex>
                <scale>3</scale>
                <isMean>true</isMean>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.PowerFactor</name>
                <registerIndex>6278</registerIndex>
                <scale>3</scale>
                <isMean>true</isMean>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.PowerFactor</name>
                <registerIndex>6279</registerIndex>
                <scale>3</scale>
                <isMean>true</isMean>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.Frequency</name>
                <registerIndex>6280</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <divider>100</divider>
            </SensorDefine>
            <ComputeSensorDefine>
                <name>ELM.ZeroCurrent</name>
                <highPropertyDefines>
                    <name>ELM.ZeroCurrent_h</name>
                    <registerIndex>6281</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>1000</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ZeroCurrent_l</name>
                    <registerIndex>6282</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                    <divider>1000</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>

            <CommonDefine>
                <name>ELM.A.ApparentPower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6240</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.B.ApparentPower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6243</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.C.ApparentPower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6246</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.ApparentPower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6249</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>ELM.A.ActivePower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6252</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.B.ActivePower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6255</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.C.ActivePower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6258</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.ActivePower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6261</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>ELM.A.ReactivePower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6264</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.B.ReactivePower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6267</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.C.ReactivePower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6270</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>ELM.ReactivePower</name>
                <commandName>cmd_r2_em1_03_1848_45_${object.index}</commandName>
                <index>6273</index>
                <length>3</length>
                <divider>1000</divider>
                <precision>3</precision>
                <isMean>false</isMean>
                <calcList>
                    <longCalc>
                        <inputType>shortList</inputType>
                        <highHead>true</highHead>
                    </longCalc>
                </calcList>
            </CommonDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
