<linked-list>
<#list amsUpsList as object>
    <DzRequest>
        <name>cmd_r2_ups_d${object.index}_get_sys_analog</name>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>1</addr>
        <ver>17</ver>
        <commandType>10817</commandType>
        <ctrlData></ctrlData>
    </DzRequest>
    <DzRequest>
        <name>cmd_r2_ups_d${object.index}_get_di</name>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>1</addr>
        <ver>17</ver>
        <commandType>10819</commandType>
        <ctrlData></ctrlData>
    </DzRequest>
    <DzRequest>
        <name>cmd_r2_ups_d${object.index}_get_alarm</name>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>1</addr>
        <ver>17</ver>
        <commandType>10820</commandType>
        <ctrlData></ctrlData>
    </DzRequest>
    <DzRequest>
        <name>cmd_r2_ups_d${object.index}_get_analog1</name>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>1</addr>
        <ver>17</ver>
        <commandType>10977</commandType>
        <ctrlData></ctrlData>
    </DzRequest>
    <DzRequest>
        <name>cmd_r2_ups_d${object.index}_get_analog2</name>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>1</addr>
        <ver>17</ver>
        <commandType>10978</commandType>
        <ctrlData>00</ctrlData>
    </DzRequest>
    <DzRequest>
        <name>cmd_r2_ups_d${object.index}_get_analog3</name>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>1</addr>
        <ver>17</ver>
        <commandType>10979</commandType>
        <ctrlData></ctrlData>
    </DzRequest>
</#list>
</linked-list>
