<linked-list>
<#list amsUpsList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <CommonDefine>
                <name>UPS.Input.LineVoltage.AB</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>2</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Input.LineVoltage.BC</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>10</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Input.LineVoltage.CA</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>18</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.A.Voltage</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>26</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.B.Voltage</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>34</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.C.Voltage</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>42</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.A.Current</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>50</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.B.Current</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>58</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.C.Current</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>66</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.Frequency</name>
                <commandName>cmd_r2_ups_d${object.index}_get_sys_analog</commandName>
                <index>82</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>UPS.Input.A.Current</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog1</commandName>
                <index>28</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Input.B.Current</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog1</commandName>
                <index>36</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Input.C.Current</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog1</commandName>
                <index>44</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Input.Frequency</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog1</commandName>
                <index>52</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Bypass.A.Voltage</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog1</commandName>
                <index>68</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Bypass.B.Voltage</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog1</commandName>
                <index>76</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Bypass.C.Voltage</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog1</commandName>
                <index>84</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Bypass.Frequency</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog1</commandName>
                <index>92</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Battery.Current</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog1</commandName>
                <index>100</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>UPS.Output.A.PowerFactor</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>4</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.B.PowerFactor</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>12</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.C.PowerFactor</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>20</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.A.PeakRate</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>28</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.B.PeakRate</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>36</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.C.PeakRate</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>44</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.A.ActivePower</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>44</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.B.ActivePower</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>52</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.C.ActivePower</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>60</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.A.ApparentPower</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>68</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.B.ApparentPower</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>76</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.C.ApparentPower</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>84</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.A.LoadRate</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>92</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.B.LoadRate</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>100</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.C.LoadRate</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog2</commandName>
                <index>108</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>UPS.Output.A.ReactivePower</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog3</commandName>
                <index>4</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.B.ReactivePower</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog3</commandName>
                <index>12</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Output.C.ReactivePower</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog3</commandName>
                <index>20</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Battery.ReserveTime</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog3</commandName>
                <index>100</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Battery.Temperature</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog3</commandName>
                <index>108</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Temperature</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog3</commandName>
                <index>116</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Battery.Agingcoefficient</name>
                <commandName>cmd_r2_ups_d${object.index}_get_analog3</commandName>
                <index>124</index>
                <length>8</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <ieee32FloatCalc>
                        <highHead>false</highHead>
                    </ieee32FloatCalc>
                </calcList>
            </CommonDefine>

            <CommonDefine>
                <name>UPS.Mode.PowerSupply</name>
                <commandName>cmd_r2_ups_d${object.index}_get_di</commandName>
                <index>2</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="1" target="1"></map>
                        <map val="2" target="2"></map>
                        <map val="0xe9" target="0"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.State.Battery.Test</name>
                <commandName>cmd_r2_ups_d${object.index}_get_di</commandName>
                <index>6</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0xe0" target="1"></map>
                        <map val="0xe1" target="0"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.State.PowerSupply</name>
                <commandName>cmd_r2_ups_d${object.index}_get_di</commandName>
                <index>8</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0xe0" target="1"></map>
                        <map val="0xe1" target="2"></map>
                        <map val="0xe2" target="0"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.State.StartUp</name>
                <commandName>cmd_r2_ups_d${object.index}_get_di</commandName>
                <index>10</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0xe1" target="1"></map>
                        <map val="0xe0" target="0"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.State.Rectifier.PowerSupply</name>
                <commandName>cmd_r2_ups_d${object.index}_get_di</commandName>
                <index>12</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0xe0" target="0"></map>
                        <map val="0xe1" target="1"></map>
                        <map val="0xe2" target="2"></map>
                        <map val="0xe3" target="3"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.State.Generator.Access</name>
                <commandName>cmd_r2_ups_d${object.index}_get_di</commandName>
                <index>14</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0xe0" target="1"></map>
                        <map val="0xe1" target="0"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.State.Inverter.Sync</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>2</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="3" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Fault.MainCircuit.Voltage</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>4</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Fault.Rectifier</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>6</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Fault.Inverter</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>8</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Alarm.Bypass.Overlimit</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>10</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xE0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.State.BatteryPack</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>12</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0x01" target="1"></map>
                        <map val="0x02" target="2"></map>
                        <map val="0xf0" target="3"></map>
                        <map val="0xe1" target="4"></map>
                        <map val="0xe2" target="5"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Fault.Fan</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>48</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Alarm.Environment.Temperature</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>104</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Fault.EmergencyShutdown</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>102</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Fault.Bypass.Thyristor</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>52</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Fault.Bypass.PhaseReversed</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>68</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Alarm.Bypass.Current</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>86</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
            <CommonDefine>
                <name>UPS.Fault.Bypass.AbnormalShutdown</name>
                <commandName>cmd_r2_ups_d${object.index}_get_alarm</commandName>
                <index>62</index>
                <length>2</length>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <calcList>
                    <asciiToHexCalc></asciiToHexCalc>
                    <mapIntCalc except="0">
                        <map val="0" target="0"></map>
                        <map val="0xf0" target="1"></map>
                    </mapIntCalc>
                </calcList>
            </CommonDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
