<linked-list>
<#list pdcList as object>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>PDC.C1.A.LoadRate</propertyPath>
            </SimpleSensorValue>
            <limit>85</limit>
            <name>回路1A相总负载</name>
        </GreaterThanRule>
        <id>10032</id>
        <title>超载告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}超过{l:limit}%，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>PDC.C1.B.LoadRate</propertyPath>
            </SimpleSensorValue>
            <limit>85</limit>
            <name>回路1B相总负载</name>
        </GreaterThanRule>
        <id>10033</id>
        <title>超载告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}超过{l:limit}%，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>PDC.C1.C.LoadRate</propertyPath>
            </SimpleSensorValue>
            <limit>85</limit>
            <name>回路1C相总负载</name>
        </GreaterThanRule>
        <id>10034</id>
        <title>超载告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}超过{l:limit}%，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>PDC.C2.A.LoadRate</propertyPath>
            </SimpleSensorValue>
            <limit>85</limit>
            <name>回路2A相总负载</name>
        </GreaterThanRule>
        <id>10035</id>
        <title>超载告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}超过{l:limit}%，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>PDC.C2.B.LoadRate</propertyPath>
            </SimpleSensorValue>
            <limit>85</limit>
            <name>回路2B相总负载</name>
        </GreaterThanRule>
        <id>10036</id>
        <title>超载告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}超过{l:limit}%，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>PDC.C2.C.LoadRate</propertyPath>
            </SimpleSensorValue>
            <limit>85</limit>
            <name>回路2C相总负载</name>
        </GreaterThanRule>
        <id>10037</id>
        <title>超载告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}超过{l:limit}%，达到{l:current}</descriptionPattern>
    </AlertDefine>
</#list>
</linked-list>
