<linked-list>
<#list pduList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        03 03 14 08 AA 00 00 00 00 00 00 00 00 13 86 00 00 00 00 00 00 00 00 59 6B
        01 03 14 08 AD 00 00 00 00 00 00 00 00 13 87 00 00 00 00 0A 43 01 D5 4A F5

        <iSensorDefines>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.Voltage</name>
                <registerIndex>2</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_left_AI_2_10</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.Current</name>
                <registerIndex>3</registerIndex>
                <scale>3</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_left_AI_2_10</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.ActivePower</name>
                <registerIndex>4</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_left_AI_2_10</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.Temperature</name>
                <registerIndex>10</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_left_AI_2_10</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.Humidity</name>
                <registerIndex>11</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_left_AI_2_10</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.Voltage</name>
                <registerIndex>2</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_right_AI_2_10</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.Current</name>
                <registerIndex>3</registerIndex>
                <scale>3</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_right_AI_2_10</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.ActivePower</name>
                <registerIndex>4</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_right_AI_2_10</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.Temperature</name>
                <registerIndex>10</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_right_AI_2_10</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.Humidity</name>
                <registerIndex>11</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>cmd_c1_pdu_${object.index}_right_AI_2_10</commandName>
                <divider>10</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
