<linked-list>
<#list pfjList as object>
    <deviceActionDefine>
        <deviceId>${object.deviceId}</deviceId>
        <actionDefines>
            <actionDefine>
                <actionName>start</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.${object.index}.StartUp.On</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>stop</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.${object.index}.StartUp.OFF</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>auto</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.${object.index}.Model.Auto</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>low</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.${object.index}.Model.Low</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>middle</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.${object.index}.Model.Middle</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>high</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.${object.index}.Model.High</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
        </actionDefines>
    </deviceActionDefine>
</#list>
</linked-list>
