<linked-list>
<#list pfjList as object>
    <DoRequest>
        <name>NewFan.${object.index}.StartUp.On</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>0</regNum>
        <busId>${object.busId}</busId>
        <do__state>1</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.${object.index}.StartUp.OFF</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>0</regNum>
        <busId>${object.busId}</busId>
        <do__state>0</do__state>
    </DoRequest>
    <ModbusSetOneRequest>
        <name>NewFan.${object.index}.Model.Auto</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>1</regNum>
        <busId>${object.busId}</busId>
        <setValue>1</setValue>
    </ModbusSetOneRequest>
    <ModbusSetOneRequest>
        <name>NewFan.${object.index}.Model.Low</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>1</regNum>
        <busId>${object.busId}</busId>
        <setValue>2</setValue>
    </ModbusSetOneRequest>
    <ModbusSetOneRequest>
        <name>NewFan.${object.index}.Model.Middle</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>1</regNum>
        <busId>${object.busId}</busId>
        <setValue>4</setValue>
    </ModbusSetOneRequest>
    <ModbusSetOneRequest>
        <name>NewFan.${object.index}.Model.High</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>1</regNum>
        <busId>${object.busId}</busId>
        <setValue>8</setValue>
    </ModbusSetOneRequest>
</#list>
</linked-list>
