<linked-list>
<#list sndAcList as object>
    <AlertDefine>
        <EqualRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.RunState</propertyPath>
            </SimpleSensorValue>
            <name>空调运行状态</name>
            <limit>0</limit>
        </EqualRule>
        <id>10031</id>
        <title>关机</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}报警</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Module.1.ReturnAir.Temperature</propertyPath>
            </SimpleSensorValue>
            <limit>35</limit>
            <name>温度</name>
        </GreaterThanRule>
        <id>10010</id>
        <title>回风温度过高</title>
        <category>0</category>
        <level>0</level>
        <descriptionPattern>{l:name}超过{l:limit}度，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Module.1.ReturnAir.Humidity</propertyPath>
            </SimpleSensorValue>
            <limit>90</limit>
            <name>湿度</name>
        </GreaterThanRule>
        <id>10010</id>
        <title>回风湿度过高</title>
        <category>0</category>
        <level>0</level>
        <descriptionPattern>{l:name}超过{l:limit}度，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Module.1.SupplyAir.Temperature</propertyPath>
            </SimpleSensorValue>
            <limit>35</limit>
            <name>温度</name>
        </GreaterThanRule>
        <id>10010</id>
        <title>送风温度过高</title>
        <category>0</category>
        <level>0</level>
        <descriptionPattern>{l:name}超过{l:limit}度，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Module.1.SupplyAir.Humidity</propertyPath>
            </SimpleSensorValue>
            <limit>90</limit>
            <name>湿度</name>
        </GreaterThanRule>
        <id>10010</id>
        <title>送风湿度过高</title>
        <category>0</category>
        <level>0</level>
        <descriptionPattern>{l:name}超过{l:limit}度，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Indoor.Temperature</propertyPath>
            </SimpleSensorValue>
            <limit>35</limit>
            <name>温度</name>
        </GreaterThanRule>
        <id>10010</id>
        <title>超温报警</title>
        <category>0</category>
        <level>0</level>
        <descriptionPattern>{l:name}超过{l:limit}度，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Indoor.Humidity</propertyPath>
            </SimpleSensorValue>
            <limit>90</limit>
            <name>湿度</name>
        </GreaterThanRule>
        <id>10014</id>
        <title>超湿报警</title>
        <category>0</category>
        <level>0</level>
        <descriptionPattern>{l:name}超过{l:limit}%，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <GreaterThanRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Module.1.SupplyAir.Temperature</propertyPath>
            </SimpleSensorValue>
            <limit>35</limit>
            <name>温度</name>
        </GreaterThanRule>
        <id>10010</id>
        <title>超温报警</title>
        <category>0</category>
        <level>0</level>
        <descriptionPattern>{l:name}超过{l:limit}度，达到{l:current}</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <EqualRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Module.1.Alarm.Filter.Fault</propertyPath>
            </SimpleSensorValue>
            <name>空调过滤器阻塞状态</name>
            <limit>1</limit>
        </EqualRule>
        <id>10018</id>
        <title>过滤器阻塞</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}报警</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <EqualRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Alarm.Flood</propertyPath>
            </SimpleSensorValue>
            <name>水浸状态</name>
            <limit>1</limit>
        </EqualRule>
        <id>10017</id>
        <title>水浸告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}报警</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <EqualRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Circuit1.HighPressureAlarm</propertyPath>
            </SimpleSensorValue>
            <name>空调回路1高压告警</name>
            <limit>1</limit>
        </EqualRule>
        <id>10028</id>
        <title>回路1高压告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}报警</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <EqualRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Circuit1.LowPressureAlarm</propertyPath>
            </SimpleSensorValue>
            <name>空调回路1低压告警</name>
            <limit>1</limit>
        </EqualRule>
        <id>10028</id>
        <title>回路1低压告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}报警</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <EqualRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Circuit2.HighPressureAlarm</propertyPath>
            </SimpleSensorValue>
            <name>空调回路2高压告警</name>
            <limit>1</limit>
        </EqualRule>
        <id>10028</id>
        <title>回路2高压告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}报警</descriptionPattern>
    </AlertDefine>
    <AlertDefine>
        <EqualRule>
            <SimpleSensorValue>
                <deviceId>${object.deviceId}</deviceId>
                <propertyPath>CRAC.Circuit2.LowPressureAlarm</propertyPath>
            </SimpleSensorValue>
            <name>空调回路2低压告警</name>
            <limit>1</limit>
        </EqualRule>
        <id>10028</id>
        <title>回路2低压告警</title>
        <category>1</category>
        <level>2</level>
        <descriptionPattern>{l:name}报警</descriptionPattern>
    </AlertDefine>
</#list>
</linked-list>