<linked-list>
<#list sndAcList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>CRAC.RunState</name>
                <registerIndex>1</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Module.1.Compressor.1.RunState</name>
                <registerIndex>2</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Module.1.Compressor.2.RunState</name>
                <registerIndex>3</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Module.2.Compressor.1.RunState</name>
                <registerIndex>4</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Module.2.Compressor.2.RunState</name>
                <registerIndex>5</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Module.1.Heater.1.RunState</name>
                <registerIndex>6</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Module.1.Heater.2.RunState</name>
                <registerIndex>7</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Module.1.Dehumidify.RunState</name>
                <registerIndex>10</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Module.1.Humidify.RunState</name>
                <registerIndex>11</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>

            <MutexSensorDefine>
                <name>CRAC.Alarm.ReturnAir.Temperature</name>
                <scale>0</scale>
                <isMean>false</isMean>
                <defaultVal>0</defaultVal>
                <sensorValMaps>
                    <sensorValMap>
                        <SensorDefine>
                            <name>ReturnAirTemperatureHighAlarm</name>
                            <registerIndex>21</registerIndex>
                            <scale>0</scale>
                            <isMean>false</isMean>
                            <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                            <divider>1</divider>
                        </SensorDefine>
                        <mutexMap>
                            <map val="1" target="2"/>
                        </mutexMap>
                    </sensorValMap>
                    <sensorValMap>
                        <SensorDefine>
                            <name>ReturnAirTemperatureLowAlarm</name>
                            <registerIndex>22</registerIndex>
                            <scale>0</scale>
                            <isMean>false</isMean>
                            <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                            <divider>1</divider>
                        </SensorDefine>
                        <mutexMap>
                            <map val="1" target="1"/>
                        </mutexMap>
                    </sensorValMap>
                </sensorValMaps>
            </MutexSensorDefine>

            <MutexSensorDefine>
                <name>CRAC.Alarm.ReturnAir.Humidity</name>
                <scale>0</scale>
                <isMean>false</isMean>
                <defaultVal>0</defaultVal>
                <sensorValMaps>
                    <sensorValMap>
                        <SensorDefine>
                            <name>ReturnAirHumidityHighAlarm</name>
                            <registerIndex>23</registerIndex>
                            <scale>0</scale>
                            <isMean>false</isMean>
                            <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                            <divider>1</divider>
                        </SensorDefine>
                        <mutexMap>
                            <map val="1" target="2"/>
                        </mutexMap>
                    </sensorValMap>
                    <sensorValMap>
                        <SensorDefine>
                            <name>ReturnAirHumidityLowAlarm</name>
                            <registerIndex>24</registerIndex>
                            <scale>0</scale>
                            <isMean>false</isMean>
                            <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                            <divider>1</divider>
                        </SensorDefine>
                        <mutexMap>
                            <map val="1" target="1"/>
                        </mutexMap>
                    </sensorValMap>
                </sensorValMaps>
            </MutexSensorDefine>

            <SensorDefine>
                <name>CRAC.Module.1.Alarm.Filter.Fault</name>
                <registerIndex>26</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Smoke</name>
                <registerIndex>37</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Flood</name>
                <registerIndex>27</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_1_0_100</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <name>CRAC.Indoor.Temperature</name>
                <registerIndex>1</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_3_0_50</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Outdoor.Temperature</name>
                <registerIndex>2</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_3_0_50</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Module.1.SupplyAir.Temperature</name>
                <registerIndex>3</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_3_0_50</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Indoor.Humidity</name>
                <registerIndex>6</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_3_0_50</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Threshold.ReturnAir.Temperature.High</name>
                <registerIndex>26</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_3_0_50</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Threshold.ReturnAir.Temperature.Low</name>
                <registerIndex>27</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>modbus_${object.deviceId}_${object.port}_${object.index}_3_0_50</commandName>
                <divider>1</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
