<linked-list>
<#list sndUpsList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SnmpSensorDefine>
                <name>UPS.Battery.ReserveCapacity</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.2.2.1.0</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Battery.Temperature</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.2.2.2.0</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Battery.ReserveTime</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.2.2.3.0</oid>
                <divider>60000</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Input.Frequency</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.3.2.4.0</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.Frequency</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.2.1.4.1</oid>
                <divider>10</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.A.Voltage</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.3.1.1.1</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.B.Voltage</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.3.1.1.2</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.C.Voltage</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.3.1.1.3</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.A.Current</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.4.1.1.1</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.B.Current</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.4.1.1.2</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.C.Current</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.4.1.1.3</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.A.ActivePower</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.13.1.1.1</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.B.ActivePower</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.13.1.1.2</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.C.ActivePower</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.13.1.1.3</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.A.ApparentPower</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.20.1.1.1</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.B.ApparentPower</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.20.1.1.2</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Output.C.ApparentPower</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.9.3.3.1.20.1.1.3</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.State.BatteryPack</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.2.1.1.0</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <mutexMap except="1">
                    <map val="2" target="0"/>
                </mutexMap>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.Fault.Output.Comunicate</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.8.1.0</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <mutexMap except="1">
                    <map val="1" target="0"/>
                </mutexMap>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.State.Battery.Test</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.2.1.1.0</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
                <mutexMap except="0">
                    <map val="9" target="1"/>
                </mutexMap>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>UPS.State.PowerSupply</name>
                <commandName>ups_galaxy_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.1.2.2.17.0</oid>
                <divider>1</divider>
                <precision>2</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
