<?xml version="1.0" encoding="UTF-8"?>

<linked-list> 
  <DeviceDefine> 
    <deviceId>${deviceId}</deviceId>
    <iSensorDefines> 
      <SensorDefine> 
        <name>U.1.State</name>  
        <isState>true</isState>
        <registerIndex>3</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.2.State</name>  
        <isState>true</isState>
        <registerIndex>4</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.3.State</name>  
        <isState>true</isState>
        <registerIndex>5</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.4.State</name>  
        <isState>true</isState>
        <registerIndex>6</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.5.State</name>  
        <isState>true</isState>
        <registerIndex>7</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.6.State</name>  
        <isState>true</isState>
        <registerIndex>8</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.7.State</name>  
        <isState>true</isState>
        <registerIndex>9</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.8.State</name>  
        <isState>true</isState>
        <registerIndex>10</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.9.State</name>  
        <isState>true</isState>
        <registerIndex>11</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.10.State</name>  
        <isState>true</isState>
        <registerIndex>12</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.11.State</name>  
        <isState>true</isState>
        <registerIndex>13</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.12.State</name>  
        <isState>true</isState>
        <registerIndex>14</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.13.State</name>  
        <isState>true</isState>
        <registerIndex>15</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.14.State</name>  
        <isState>true</isState>
        <registerIndex>16</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.15.State</name>  
        <isState>true</isState>
        <registerIndex>17</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.16.State</name>  
        <isState>true</isState>
        <registerIndex>18</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.17.State</name>  
        <isState>true</isState>
        <registerIndex>19</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.18.State</name>  
        <isState>true</isState>
        <registerIndex>20</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.19.State</name>  
        <isState>true</isState>
        <registerIndex>21</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.20.State</name>  
        <isState>true</isState>
        <registerIndex>22</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.21.State</name>  
        <isState>true</isState>
        <registerIndex>23</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.22.State</name>  
        <isState>true</isState>
        <registerIndex>24</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.23.State</name>  
        <isState>true</isState>
        <registerIndex>25</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.24.State</name>  
        <isState>true</isState>
        <registerIndex>26</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.25.State</name>  
        <isState>true</isState>
        <registerIndex>27</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.26.State</name>  
        <isState>true</isState>
        <registerIndex>28</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.27.State</name>  
        <isState>true</isState>
        <registerIndex>29</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.28.State</name>  
        <isState>true</isState>
        <registerIndex>30</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.29.State</name>  
        <isState>true</isState>
        <registerIndex>31</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.30.State</name>  
        <isState>true</isState>
        <registerIndex>32</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.31.State</name>  
        <isState>true</isState>
        <registerIndex>33</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.32.State</name>  
        <isState>true</isState>
        <registerIndex>34</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.33.State</name>  
        <isState>true</isState>
        <registerIndex>35</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.34.State</name>  
        <isState>true</isState>
        <registerIndex>36</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.35.State</name>  
        <isState>true</isState>
        <registerIndex>37</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.36.State</name>  
        <isState>true</isState>
        <registerIndex>38</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.37.State</name>  
        <isState>true</isState>
        <registerIndex>39</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.38.State</name>  
        <isState>true</isState>
        <registerIndex>40</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.39.State</name>  
        <isState>true</isState>
        <registerIndex>41</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.40.State</name>  
        <isState>true</isState>
        <registerIndex>42</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.41.State</name>  
        <isState>true</isState>
        <registerIndex>43</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.42.State</name>  
        <isState>true</isState>
        <registerIndex>44</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.43.State</name>  
        <isState>true</isState>
        <registerIndex>45</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.44.State</name>  
        <isState>true</isState>
        <registerIndex>46</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.45.State</name>  
        <isState>true</isState>
        <registerIndex>47</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>U.46.State</name>  
        <isState>true</isState>
        <registerIndex>48</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>ubit_q1_${deviceId}_1</commandName>
        <divider>1</divider> 
      </SensorDefine> 
    </iSensorDefines> 
  </DeviceDefine> 
</linked-list>
