<linked-list>
    <#list pduList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <Byte4ToFloatComputeSensorDefine>
                <name>RACK.BackDoor.PDU.1.Voltage</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.MainSupply.Voltage.H</name>
                    <registerIndex>0</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.MainSupply.Voltage.L</name>
                    <registerIndex>1</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>RACK.BackDoor.PDU.1.Current</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.MainSupply.Current.H</name>
                    <registerIndex>2</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.MainSupply.Current.L</name>
                    <registerIndex>3</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>RACK.BackDoor.PDU.1.ActivePower</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.ActivePower.H</name>
                    <registerIndex>6</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.ActivePower.L</name>
                    <registerIndex>7</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>RACK.BackDoor.PDU.1.Humidity</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Humidity.H</name>
                    <registerIndex>14</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Humidity.L</name>
                    <registerIndex>15</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>RACK.BackDoor.PDU.1.Temperature</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Temperature.H</name>
                    <registerIndex>16</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Temperature.L</name>
                    <registerIndex>17</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>RACK.BackDoor.PDU.1.ActiveEnergy</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.ElectricQuantity.H</name>
                    <registerIndex>18</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.ElectricQuantity.L</name>
                    <registerIndex>19</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Temperature.UpperLimit</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Temperature.UpperLimit.H</name>
                    <registerIndex>20</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Temperature.UpperLimit.L</name>
                    <registerIndex>21</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Voltage.UpperLimit</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Voltage.UpperLimit.H</name>
                    <registerIndex>22</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Voltage.UpperLimit.L</name>
                    <registerIndex>23</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Voltage.LowerLimit</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Voltage.LowerLimit.H</name>
                    <registerIndex>24</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Voltage.LowerLimit.L</name>
                    <registerIndex>25</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Current.UpperLimit</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Current.UpperLimit.H</name>
                    <registerIndex>26</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Current.UpperLimit.L</name>
                    <registerIndex>27</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Current.LowerLimit</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Current.LowerLimit.H</name>
                    <registerIndex>30</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_30_8</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Current.LowerLimit.L</name>
                    <registerIndex>31</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_30_8</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Temperature.LowerLimit</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Temperature.LowerLimit.H</name>
                    <registerIndex>32</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_30_8</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Temperature.LowerLimit.L</name>
                    <registerIndex>33</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_30_8</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Humidity.UpperLimit</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Humidity.UpperLimit.H</name>
                    <registerIndex>34</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_30_8</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Humidity.UpperLimit.L</name>
                    <registerIndex>35</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_30_8</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Humidity.LowerLimit</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Humidity.LowerLimit.H</name>
                    <registerIndex>36</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_30_8</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Humidity.LowerLimit.L</name>
                    <registerIndex>37</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_30_8</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Nominal.Voltage</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Nominal.Voltage.H</name>
                    <registerIndex>3926</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_3926_4</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Nominal.Voltage.L</name>
                    <registerIndex>3927</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_3926_4</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.Nominal.Current</name>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Nominal.Current.H</name>
                    <registerIndex>3928</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_3926_4</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>PDU.Nominal.Current.L</name>
                    <registerIndex>3929</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_${object.index}_3_3926_4</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <SensorDefine>
                <isState>true</isState>
                <name>PDU.Temperature.Over</name>
                <registerIndex>2</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_spem_${object.index}_2_2_4</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <isState>true</isState>
                <name>PDU.Current.Over</name>
                <registerIndex>3</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_spem_${object.index}_2_2_4</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <isState>true</isState>
                <name>PDU.Voltage.Over</name>
                <registerIndex>4</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_spem_${object.index}_2_2_4</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <isState>true</isState>
                <name>PDU.Voltage.Loss</name>
                <registerIndex>5</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_spem_${object.index}_2_2_4</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <isState>true</isState>
                <name>PDU.Current.Lower</name>
                <registerIndex>10</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_spem_${object.index}_2_10_4</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <isState>true</isState>
                <name>PDU.Temperature.Lower</name>
                <registerIndex>11</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_spem_${object.index}_2_10_4</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <isState>true</isState>
                <name>PDU.Humidity.Over</name>
                <registerIndex>12</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_spem_${object.index}_2_10_4</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <isState>true</isState>
                <name>PDU.Humidity.Lower</name>
                <registerIndex>13</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_spem_${object.index}_2_10_4</commandName>
                <divider>1</divider>
            </SensorDefine>


        </iSensorDefines>
    </DeviceDefine>
    </#list>
</linked-list>