<linked-list>
  <ModbusRequest>
    <name>crac_q1_#{devid}_A#{busid}</name>
    <destinationHost>#{ip}</destinationHost>
    <port>#{port}</port>
    <busId>#{busid}</busId>
    <commandType>2</commandType>
    <registerNumber>12</registerNumber>
    <length>88</length>
  </ModbusRequest>
  <ModbusRequest>
    <name>crac_q2_#{devid}_A#{busid}</name>
    <destinationHost>#{ip}</destinationHost>
    <port>#{port}</port>
    <busId>#{busid}</busId>
    <commandType>4</commandType>
    <registerNumber>1</registerNumber>
    <length>28</length>
  </ModbusRequest>
  <ModbusRequest>
    <name>crac_q3_#{devid}_A#{busid}</name>
    <destinationHost>#{ip}</destinationHost>
    <port>#{port}</port>
    <busId>#{busid}</busId>
    <commandType>4</commandType>
    <registerNumber>63</registerNumber>
    <length>1</length>
  </ModbusRequest>
  <ModbusRequest>
    <name>crac_q4_#{devid}_A#{busid}</name>
    <destinationHost>#{ip}</destinationHost>
    <port>#{port}</port>
    <busId>#{busid}</busId>
    <commandType>4</commandType>
    <registerNumber>130</registerNumber>
    <length>11</length>
  </ModbusRequest>
  <ModbusRequest>
    <name>crac_q5_#{devid}_A#{busid}</name>
    <destinationHost>#{ip}</destinationHost>
    <port>#{port}</port>
    <busId>#{busid}</busId>
    <commandType>4</commandType>
    <registerNumber>113</registerNumber>
    <length>5</length>
  </ModbusRequest>
</linked-list>