<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<linked-list>
  <DeviceDefine>
    <deviceId>#{devid}</deviceId>
    <iSensorDefines>
      <SensorDefine>
        <name>CRAC.State.SoftShutDown</name>
        <registerIndex>67</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.LocalShutDown</name>
        <registerIndex>69</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.MonitorShutDown</name>
        <registerIndex>70</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.RemoteShutDown</name>
        <registerIndex>71</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Refrig</name>
        <registerIndex>81</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Heat</name>
        <registerIndex>82</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Humid</name>
        <registerIndex>83</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Dehumid</name>
        <registerIndex>84</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Fan1</name>
        <registerIndex>73</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Fan2</name>
        <registerIndex>74</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Fan3</name>
        <registerIndex>75</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Fan4</name>
        <registerIndex>76</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.PumpOutput</name>
        <registerIndex>12</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.CompressorOutput</name>
        <registerIndex>13</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.HeaterOutput</name>
        <registerIndex>14</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.FanOutput</name>
        <registerIndex>15</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.HumidOutput</name>
        <registerIndex>16</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.CommonAlarmOutput</name>
        <registerIndex>17</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.LiquidSolenoidOutput</name>
        <registerIndex>19</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.HighPressure</name>
        <registerIndex>24</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.LowPressure</name>
        <registerIndex>25</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.HighPressure.Abnormal</name>
        <registerIndex>26</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.Exhaust.Temperature.High</name>
        <registerIndex>27</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.Exhaust.Temperature.Over</name>
        <registerIndex>28</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.ReturnAir.Temperature.Over</name>
        <registerIndex>29</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.OutAir.Temperature.Less</name>
        <registerIndex>30</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.OutAir.Temperature.Over</name>
        <registerIndex>31</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.ReturnAir.Humidity.Over</name>
        <registerIndex>32</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.ReturnAir.Humidity.Less</name>
        <registerIndex>33</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.Pressure.High.Lock</name>
        <registerIndex>34</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.Pressure.Low.Lock</name>
        <registerIndex>35</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.Exhaust.Temperature.High.Lock</name>
        <registerIndex>36</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.Exhaust.Temperature.Over.LowLock</name>
        <registerIndex>37</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.Power.Loss</name>
        <registerIndex>38</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.Power.Voltage.Over</name>
        <registerIndex>39</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.Power.Voltage.Less</name>
        <registerIndex>40</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.Power.Phase.Miss</name>
        <registerIndex>41</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.Flood</name>
        <registerIndex>42</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.WaterLevel.High</name>
        <registerIndex>43</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.FilterClog</name>
        <registerIndex>44</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.Filter.Maintenance</name>
        <registerIndex>45</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.Air.Loss</name>
        <registerIndex>46</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Lock.Sensor.LowPressure</name>
        <registerIndex>47</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Sensor.ReturnAi.Temperature</name>
        <registerIndex>51</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Sensor.ReturnAir.Humidity</name>
        <registerIndex>52</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Sensor.AirDifference.Temperature</name>
        <registerIndex>53</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Sensor.OutAir.Temperature</name>
        <registerIndex>54</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Sensor.Remote.Temperature</name>
        <registerIndex>55</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Sensor.HighPressure</name>
        <registerIndex>56</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.ElectricHeating</name>
        <registerIndex>57</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Sensor.ExhaustTemperature</name>
        <registerIndex>86</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Fan.Power</name>
        <registerIndex>87</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.EEV.Communication</name>
        <registerIndex>88</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.NotSelectRefrigerant</name>
        <registerIndex>89</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Refrigerant.Inadequate</name>
        <registerIndex>90</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Sensor.SuctionTemperature</name>
        <registerIndex>91</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Sensor.LowPressure</name>
        <registerIndex>92</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Compressor.DriveCommunication</name>
        <registerIndex>93</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Compressor.Drive</name>
        <registerIndex>94</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Compressor.RadiatorOver</name>
        <registerIndex>95</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Compressor.Overcurrent.Protection</name>
        <registerIndex>96</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Compressor.Phase.Protection</name>
        <registerIndex>97</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Compressor.BusVoltage</name>
        <registerIndex>98</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
<SensorDefine>
        <name>CRAC.Alarm.Humidifier</name>
        <registerIndex>99</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      
      <SensorDefine>
        <name>CRAC.OutAir.Temperature</name>
        <registerIndex>1</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.ReturnAir.Temperature</name>
        <registerIndex>6</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.ReturnAir.Humidity</name>
        <registerIndex>10</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.A.Voltage</name>
        <registerIndex>24</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q2_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.B.Voltage</name>
        <registerIndex>25</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q2_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.C.Voltage</name>
        <registerIndex>26</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q2_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Frequency</name>
        <registerIndex>27</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q2_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>

      <SensorDefine>
        <name>CRAC.Switch.State</name>
        <registerIndex>63</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q3_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.1.Temperature</name>
        <registerIndex>130</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.2.Temperature</name>
        <registerIndex>131</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.3.Temperature</name>
        <registerIndex>132</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.4.Temperature</name>
        <registerIndex>133</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.5.Temperature</name>
        <registerIndex>134</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.6.Temperature</name>
        <registerIndex>135</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.7.Temperature</name>
        <registerIndex>136</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.8.Temperature</name>
        <registerIndex>137</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.9.Temperature</name>
        <registerIndex>138</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.10.Temperature</name>
        <registerIndex>139</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Remote.Average.Temperature</name>
        <registerIndex>140</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_#{devid}_A#{busid}</commandName>
        <divider>10</divider>
      </SensorDefine>      
      <SensorDefine>
        <name>CRAC.Compressor.Capacity</name>
        <registerIndex>113</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q5_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>      
      <SensorDefine>
        <name>CRAC.Fan.Speed</name>
        <registerIndex>116</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q5_#{devid}_A#{busid}</commandName>
        <divider>1</divider>
      </SensorDefine>   
    </iSensorDefines>
  </DeviceDefine>
</linked-list>