<linked-list>
<#list acList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>CRAC.Fan.State</name>
                <registerIndex>10025</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_pex_${object.index}_2_10025_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Cooling.State</name>
                <registerIndex>10026</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_pex_${object.index}_2_10025_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.FreeCooling.State</name>
                <registerIndex>10027</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_pex_${object.index}_2_10025_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.HotWaterAndGas.State</name>
                <registerIndex>10028</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_pex_${object.index}_2_10025_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ElectricReheat.State</name>
                <registerIndex>10029</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_pex_${object.index}_2_10025_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Humidifier.State</name>
                <registerIndex>10030</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_pex_${object.index}_2_10025_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Dehumidifier.State</name>
                <registerIndex>10031</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_pex_${object.index}_2_10025_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Buzzer.Status</name>
                <registerIndex>10032</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_pex_${object.index}_2_10025_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Fan.Overload</name>
                <registerIndex>10034</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.AirFlow.Loss</name>
                <registerIndex>10035</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.WaterFlow.Loss</name>
                <registerIndex>10036</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.1.Pressure.High</name>
                <registerIndex>10037</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.1.Pressure.Low</name>
                <registerIndex>10038</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.1.Overload</name>
                <registerIndex>10039</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.1.PumpDown.Fail</name>
                <registerIndex>10040</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.Pressure.High</name>
                <registerIndex>10041</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.Pressure.Low</name>
                <registerIndex>10042</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.Overload</name>
                <registerIndex>10043</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.PumpDown.Fail</name>
                <registerIndex>10044</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Smoke</name>
                <registerIndex>10047</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Water</name>
                <registerIndex>10048</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Humidifier.Issue</name>
                <registerIndex>10049</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Indoor.TH.Issue</name>
                <registerIndex>10053</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.Power.Lose</name>
                <registerIndex>10054</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Blower.AirFlow.Lose</name>
                <registerIndex>10055</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10034_22</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Humidifier.WaterLevel.Low</name>
                <registerIndex>10058</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10058_4</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Humidifier.Current.High</name>
                <registerIndex>10059</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10058_4</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Temperature.High</name>
                <registerIndex>10060</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10058_4</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Unknow</name>
                <registerIndex>10064</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10064_2</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.CoolingWater.Temperature.High</name>
                <registerIndex>10065</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10064_2</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Indoor.Temperature.Over</name>
                <registerIndex>10067</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Indoor.Temperature.Under</name>
                <registerIndex>10068</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Indoor.Humidity.High</name>
                <registerIndex>10069</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Indoor.Humidity.Low</name>
                <registerIndex>10070</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.A.Temperature.Over</name>
                <registerIndex>10071</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.A.Temperature.Under</name>
                <registerIndex>10072</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.A.Humidity.High</name>
                <registerIndex>10073</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.A.Humidity.Low</name>
                <registerIndex>10074</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.CoolingWater.WaterFlow.Lose</name>
                <registerIndex>10075</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Filter.Block</name>
                <registerIndex>10076</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Fan.OverTime</name>
                <registerIndex>10080</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Compressor.1.OverTime</name>
                <registerIndex>10081</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Compressor.2.OverTime</name>
                <registerIndex>10082</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.FreeCooling.OverTime</name>
                <registerIndex>10083</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ElectricReheater.1.OverTime</name>
                <registerIndex>10084</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ElectricReheater.2.OverTime</name>
                <registerIndex>10085</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ElectricReheater.3.OverTime</name>
                <registerIndex>10086</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.HotWaterAndGas.OverTime</name>
                <registerIndex>10087</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Humidifier.OverTime</name>
                <registerIndex>10088</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Dehumidifier.OverTime</name>
                <registerIndex>10089</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_2_10067_23</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <name>CRAC.ReturnAir.Temperature</name>
                <registerIndex>30110</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.SupplyAir.Temperature</name>
                <registerIndex>30112</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.FreeCooling.FluidTemperature</name>
                <registerIndex>30115</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.A.Temperature</name>
                <registerIndex>30116</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.B.Temperature</name>
                <registerIndex>30117</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.C.Temperature</name>
                <registerIndex>30118</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.DigScrollComp.1.Discharge.Temperature</name>
                <registerIndex>30119</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.DigScrollComp.2.Discharge.Temperature</name>
                <registerIndex>30120</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ReturnAir.Humidity</name>
                <registerIndex>30130</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.A.Humidity</name>
                <registerIndex>30132</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.B.Humidity</name>
                <registerIndex>30133</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.C.Humidity</name>
                <registerIndex>30134</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>10</divider>
            </SensorDefine>
            <!-- 风机运行时间 小时-->
            <SensorDefine>
                <name>CRAC.Fan.RunningTime</name>
                <registerIndex>30141</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 压缩机运行时间 小时-->
            <SensorDefine>
                <name>CRAC.Compressor.1.RunningTime</name>
                <registerIndex>30142</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 压缩机运行时间 小时-->
            <SensorDefine>
                <name>CRAC.Compressor.2.RunningTime</name>
                <registerIndex>30143</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 加湿器运行 时间 -->
            <SensorDefine>
                <name>CRAC.Humidifier.RunningTime</name>
                <registerIndex>30144</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 除湿器运行 时间 -->
            <SensorDefine>
                <name>CRAC.Dehumidifier.RunningTime</name>
                <registerIndex>30145</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 自然冷却运行 时间 -->
            <SensorDefine>
                <name>CRAC.FreeCooling.RunningTime</name>
                <registerIndex>30146</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 电加热运行 时间 -->
            <SensorDefine>
                <name>CRAC.ElectricReheater.1.RunningTime</name>
                <registerIndex>30147</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ElectricReheater.2.RunningTime</name>
                <registerIndex>30148</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ElectricReheater.3.RunningTime</name>
                <registerIndex>30149</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.HotWaterAndGas.RunningTime</name>
                <registerIndex>30150</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>cmd_pex_${object.index}_4_30110_41</commandName>
                <divider>1</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>