<linked-list>
<#list upsList as object>
  <DeviceDefine>
    <deviceId>${object.deviceId}</deviceId>
    <iSensorDefines>
      <SensorDefine>
        <#--<displayName>告警状态:0未知状态，2没有告警，4存在告警警报，8存在严重告警</displayName>-->
        <name>UPS.Alert.Status</name>
        <registerIndex>0</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输出没有通电</displayName>-->
        <name>UPS.Alert.OutPut.NotPowered</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>0</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>逆变器没有被使用</displayName>-->
        <name>UPS.Alert.Inverter.NotUsed</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>1</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>硬件内部存在错误</displayName>-->
        <name>UPS.Alert.Internal.Hardware.ExistsFault</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>2</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>打开电池电源，以响应输入电源问题</displayName>-->
        <name>UPS.Battery.Usage.Status</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>4</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>电池过低告警</displayName>-->
        <name>UPS.Alert.Battery.Low.Warning</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>5</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>电量过低，Ups处于关机状态</displayName>-->
        <name>UPS.Alert.Battery.Low.Shutdown</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>6</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>旁路交流输入被用作电源</displayName>-->
        <name>UPS.Alert.Bypass.ACInput.ForPower</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>7</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>ModBus数据无效</displayName>-->
        <name>UPS.Alert.ModBusData.Not.Valid</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>8</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>串口通讯存在故障</displayName>-->
        <name>UPS.Alert.Communication.Fault</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>9</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输出过载</displayName>-->
        <name>UPS.Alert.OutPut.OverLoad</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>10</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>紧急按停</displayName>-->
        <name>UPS.Alert.Emergency.Stop</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>11</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>温度故障</displayName>-->
        <name>UPS.Alert.Temperature.Fault</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>12</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>电池要检查或外部电池监控故障</displayName>-->
        <name>UPS.Alert.Battery.CheckedOrExternalMonitor.Fault</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>13</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>通风设备故障(系统级风机存在故障)</displayName>-->
        <name>UPS.Alert.Device.Ventilation.Fault</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>14</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>负载报警故障</displayName>-->
        <name>UPS.Alert.Load.Alarm.Violation.Fault</name>
        <registerIndex>64</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>15</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>0 -功率转换器目前工作在自动测距 1 -功率转换器目前工作在变频器上</displayName>-->
        <name>UPS.Run.In.Frequency.Converter</name>
        <registerIndex>65</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>0</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>整流内部故障</displayName>-->
        <name>UPS.Alert.Rectifier.Internal.Fault</name>
        <registerIndex>65</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>9</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>由于良好电源模块的数量减少，负载保护丢失</displayName>-->
        <name>UPS.Alert.LoadProtected.Lose</name>
        <registerIndex>65</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>10</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>0-UPS未处于节能模式（效率提升模式）1-UPS以省电模式（EBM）运行</displayName>-->
        <name>UPS.Saving.Mode.Status</name>
        <registerIndex>65</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>11</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>UPS环境故障或UPS小故障</displayName>-->
        <name>UPS.Alert.Environment.Fault</name>
        <registerIndex>65</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>12</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>0-UPS未处于ECO模式 1-UPS在ECO模式下运行</displayName>-->
        <name>UPS.ECO.Mode.Status</name>
        <registerIndex>65</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>13</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>安装电池状态</displayName>-->
        <name>UPS.Installed.Battery.Status</name>
        <registerIndex>66</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>0</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>电池测试失败(错误)</displayName>-->
        <name>UPS.Alert.Battery.Test.Result</name>
        <registerIndex>66</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>2</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>电池进行测试中</displayName>-->
        <name>UPS.Battery.Test.InProgress</name>
        <registerIndex>66</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>8</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>内部电池温度超过临界阈值</displayName>-->
        <name>UPS.Alert.Internal.Battery.Temperature.Over</name>
        <registerIndex>66</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>10</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>电池开关关闭</displayName>-->
        <name>UPS.Alert.Battery.Switch</name>
        <registerIndex>66</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>15</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>主交流开关关闭</displayName>-->
        <name>UPS.Alert.Main.AC.Switch</name>
        <registerIndex>68</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>3</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>主交流不正常/电压超出范围</displayName>-->
        <name>UPS.Alert.Main.AC.Voltage.NotOk</name>
        <registerIndex>68</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>8</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>主交流故障</displayName>-->
        <name>UPS.Alert.Main.AC.Fuse</name>
        <registerIndex>68</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>9</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>主交流频率超出范围</displayName>-->
        <name>UPS.Alert.Main.AC.Frequency.OutRange</name>
        <registerIndex>68</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>11</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输入触点1存在故障</displayName>-->
        <name>UPS.Alert.Input.Contact.1.Fault</name>
        <registerIndex>69</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>5</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输入触点2存在故障</displayName>-->
        <name>UPS.Alert.Input.Contact.2.Fault</name>
        <registerIndex>69</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>6</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>电源模块冗余丢失</displayName>-->
        <name>UPS.Alert.Power.Modules.Redundancy.Lost</name>
        <registerIndex>69</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>7</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>K2S存在故障</displayName>-->
        <name>UPS.Alert.K2S.Fault</name>
        <registerIndex>69</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>8</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>K2S开关状态</displayName>-->
        <name>UPS.K2S.Switch.Status</name>
        <registerIndex>69</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>10</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>存在重叠转移故障</displayName>-->
        <name>UPS.Alert.Overlap.Transfer.Fault</name>
        <registerIndex>69</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>11</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>维修旁路状态</displayName>-->
        <name>UPS.Maintenance.Bypass.Status</name>
        <registerIndex>70</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>1</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>旁路输入功率过载</displayName>-->
        <name>UPS.Alert.Bypass.InputPower.OverLoad</name>
        <registerIndex>70</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>5</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>旁路输入存在热过载</displayName>-->
        <name>UPS.Alert.Bypass.Input.Thermal.OverLoad</name>
        <registerIndex>70</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>6</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>旁路开关处于故障状态</displayName>-->
        <name>UPS.Alert.Bypass.Switch.Fault</name>
        <registerIndex>70</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>7</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>旁路频率超出范围</displayName>-->
        <name>UPS.Alert.Bypass.Frequency.OverRange</name>
        <registerIndex>70</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>9</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>旁路电压超出范围</displayName>-->
        <name>UPS.Alert.Bypass.Voltage.OverRange</name>
        <registerIndex>70</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>10</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>旁路开关状态</displayName>-->
        <name>UPS.Bypass.Switch.Status</name>
        <registerIndex>70</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>14</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>旁路内部故障引起的硬件故障(保险丝、继电器、…)</displayName>-->
        <name>UPS.Alert.Bypass.Internal.HardWare.Fault</name>
        <registerIndex>71</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>0</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>0 - Ups与交流旁路同步 1-Ups与交流旁路不同步</displayName>-->
        <name>UPS.InverterAndAC.Bypass.DeSynchronisation.Status</name>
        <registerIndex>71</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>1</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输出开关关闭</displayName>-->
        <name>UPS.Alert.Output.Switch.Status</name>
        <registerIndex>71</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>11</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输入触点1开闭</displayName>-->
        <name>UPS.Input.Contact.1.Status</name>
        <registerIndex>72</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>0</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输入触点2开闭</displayName>-->
        <name>UPS.Input.Contact.2.Status</name>
        <registerIndex>72</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>1</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输入触点1COSIT开闭</displayName>-->
        <name>UPS.Input.Contact.1.COSIT.Status</name>
        <registerIndex>72</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>8</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输入触点2COSIT开闭</displayName>-->
        <name>UPS.Input.Contact.2.COSIT.Status</name>
        <registerIndex>72</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>9</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输入触点3COSIT开闭</displayName>-->
        <name>UPS.Input.Contact.3.COSIT.Status</name>
        <registerIndex>72</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>10</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>输入触点4COSIT开闭</displayName>-->
        <name>UPS.Input.Contact.4.COSIT.Status</name>
        <registerIndex>72</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>11</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>充电器故障导致硬件故障</displayName>-->
        <name>UPS.Alert.Charge.Hardware.Fault</name>
        <registerIndex>73</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>0</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>1-电池充电</displayName>-->
        <name>UPS.Battery.Charge.Status</name>
        <registerIndex>73</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>3</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>1-EBM模式功能是可用的</displayName>-->
        <name>UPS.EBM.Setting.Status</name>
        <registerIndex>74</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>0</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>1-ECO模式功能是可用的</displayName>-->
        <name>UPS.ECO.Setting.Status</name>
        <registerIndex>74</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>1</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>1-定时ECO模式功能是可用的</displayName>-->
        <name>UPS.ECO.Scheduling.Setting.Status</name>
        <registerIndex>74</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>2</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>逆变器故障</displayName>-->
        <name>UPS.Alert.Inverter.Major.Fault</name>
        <registerIndex>76</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>1</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>逆变器过载</displayName>-->
        <name>UPS.Alert.Inverter.OverLoad</name>
        <registerIndex>76</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>2</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>逆变器热过载</displayName>-->
        <name>UPS.Alert.Inverter.Thermal.OverLoad</name>
        <registerIndex>76</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>3</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>0 -无电流限制 1 -电流限制</displayName>-->
        <name>UPS.Inverter.Limitation.Status</name>
        <registerIndex>76</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>4</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>0-没有保险丝或保险丝关闭 1 -保险丝打开</displayName>-->
        <name>UPS.Fuse.Fault.Status</name>
        <registerIndex>76</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>5</routeIndex>
      </SwitchSensorDefine>
      <SwitchSensorDefine>
        <#--<displayName>短路故障</displayName>-->
        <name>UPS.Alert.Short.CirCult.Fault</name>
        <registerIndex>79</registerIndex>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A1</commandName>
        <routeIndex>1</routeIndex>
      </SwitchSensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>启用ECO模式的时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.ECO.Time.Since.Commissioning.H</name>
          <registerIndex>224</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.ECO.Time.Since.Commissioning.L</name>
          <registerIndex>225</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>UPS.ECO.Time.Since.Commissioning</name>
      </ComputeSensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>重置后启用ECO模式的时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.ECO.Time.Since.Reset.H</name>
          <registerIndex>226</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.ECO.Time.Since.Reset.L</name>
          <registerIndex>227</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>UPS.ECO.Time.Since.Reset</name>
      </ComputeSensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>调试ECO后的在线时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Time.OnLine.Since.Commissioning.ECO.H</name>
          <registerIndex>228</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Time.OnLine.Since.Commissioning.ECO.L</name>
          <registerIndex>229</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>UPS.Time.OnLine.Since.Commissioning.ECO</name>
      </ComputeSensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>重置ECO后的联机时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Time.OnLine.Since.Reset.ECO.H</name>
          <registerIndex>230</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Time.OnLine.Since.Reset.ECO.L</name>
          <registerIndex>231</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>Time.OnLine.Since.Reset.ECO</name>
      </ComputeSensorDefine>
      <SensorDefine>
        <#--<displayName>自试运行以来在ECO上运行的时间百分比</displayName>-->
        <name>UPS.Spent.Time.On.ECO.Running</name>
        <registerIndex>232</registerIndex>
        <scale>2</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>重置后在ECO上运行的时间百分比</displayName>-->
        <name>UPS.Spent.Time.On.ECO.Reset.Running</name>
        <registerIndex>233</registerIndex>
        <scale>2</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>在ECO模式下运行的时间</displayName>-->
        <name>UPS.NumberTime.Running.In.ECO</name>
        <registerIndex>234</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>每月ECO模式时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Monthly.Time.In.ECO.H</name>
          <registerIndex>235</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Monthly.Time.In.ECO.L</name>
          <registerIndex>236</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>Monthly.Time.In.ECO</name>
      </ComputeSensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>启用PSM模式的时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.PSM.Time.Since.Commissioning.H</name>
          <registerIndex>240</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.PSM.Time.Since.Commissioning.L</name>
          <registerIndex>241</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>PSM.Time.Since.Commissioning</name>
      </ComputeSensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>重置后启用PSM模式的时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.PSM.Time.Since.Reset.H</name>
          <registerIndex>242</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.PSM.Time.Since.Reset.L</name>
          <registerIndex>243</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>UPS.PSM.Time.Since.Reset</name>
      </ComputeSensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>调试PSM后的在线时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Time.OnLine.Since.Commissioning.PSM.H</name>
          <registerIndex>244</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Time.OnLine.Since.Commissioning.PSM.L</name>
          <registerIndex>245</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>UPS.Time.OnLine.Since.Commissioning.PSM</name>
      </ComputeSensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>重置PSM后的联机时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Time.OnLine.Since.Reset.PSM.H</name>
          <registerIndex>246</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Time.OnLine.Since.Reset.PSM.L</name>
          <registerIndex>247</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>UPS.Time.OnLine.Since.Reset.PSM</name>
      </ComputeSensorDefine>
      <SensorDefine>
        <#--<displayName>自试运行以来在PSM上运行的时间百分比</displayName>-->
        <name>UPS.Spent.Time.On.PSM.Running</name>
        <registerIndex>248</registerIndex>
        <scale>2</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>重置后在PSM上运行的时间百分比</displayName>-->
        <name>UPS.Spent.Time.On.PSM.Reset.Running</name>
        <registerIndex>249</registerIndex>
        <scale>2</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>在PSM模式下运行的时间</displayName>-->
        <name>UPS.NumberTime.Running.In.PSM</name>
        <registerIndex>250</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <ComputeSensorDefine>
        <#--<displayName>每月PSM模式时间</displayName>-->
        <highPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Monthly.Time.In.PSM.H</name>
          <registerIndex>251</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <#--<displayName></displayName>-->
          <name>UPS.Monthly.Time.In.PSM.L</name>
          <registerIndex>252</registerIndex>
          <scale>1</scale>
          <isMean>false</isMean>
          <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
          <divider>1.0</divider>
        </lowPropertyDefines>
        <name>UPS.Monthly.Time.In.PSM</name>
      </ComputeSensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.NumberOfG7000.In.PSM</name>
        <registerIndex>253</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Mains.Input.Phase1.Current</name>
        <registerIndex>256</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Mains.Input.Phase2.Current</name>
        <registerIndex>257</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Mains.Input.Phase3.Current</name>
        <registerIndex>258</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Bypass.Input.Phase1.Current</name>
        <registerIndex>262</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Bypass.Input.Phase2.Current</name>
        <registerIndex>263</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Bypass.Input.Phase3.Current</name>
        <registerIndex>264</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase1.Current</name>
        <registerIndex>265</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase2.Current</name>
        <registerIndex>266</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase3.Current</name>
        <registerIndex>267</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Battery.Current</name>
        <registerIndex>270</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>电源输入1至2相电压</displayName>-->
        <name>UPS.Mains.Input.Phase1ToPhase2.Voltage</name>
        <registerIndex>277</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>电源输入2至3相电压</displayName>-->
        <name>UPS.Mains.Input.Phase2ToPhase3.Voltage</name>
        <registerIndex>278</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>电源输入3至1相电压</displayName>-->
        <name>UPS.Mains.Input.Phase3ToPhase1.Voltage</name>
        <registerIndex>279</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Bypass.Input.Phase1ToNeutral.Voltage</name>
        <registerIndex>286</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Bypass.Input.Phase2ToNeutral.Voltage</name>
        <registerIndex>287</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Bypass.Input.Phase3ToNeutral.Voltage</name>
        <registerIndex>288</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>旁路输入1至2相电压</displayName>-->
        <name>UPS.Bypass.Input.Phase1ToPhase2.Voltage</name>
        <registerIndex>289</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>旁路输入2至3相电压</displayName>-->
        <name>UPS.Bypass.Input.Phase2ToPhase3.Voltage</name>
        <registerIndex>290</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>旁路输入3至1相电压</displayName>-->
        <name>UPS.Bypass.Input.Phase3ToPhase1.Voltage</name>
        <registerIndex>291</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase1ToNeutral.Voltage</name>
        <registerIndex>292</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase2ToNeutral.Voltage</name>
        <registerIndex>293</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase3ToNeutral.Voltage</name>
        <registerIndex>294</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase1ToPhase2.Voltage</name>
        <registerIndex>295</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase2ToPhase3.Voltage</name>
        <registerIndex>296</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase3ToPhase1.Voltage</name>
        <registerIndex>297</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Temperature.In.DegF</name>
        <registerIndex>299</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Temperature.In.DegC</name>
        <registerIndex>300</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Battery.Voltage</name>
        <registerIndex>301</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.OutPut.Phase1.ActivePower</name>
        <registerIndex>304</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.OutPut.Phase2.ActivePower</name>
        <registerIndex>305</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.OutPut.Phase3.ActivePower</name>
        <registerIndex>306</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.OutPut.Phase1.ApparentPower</name>
        <registerIndex>307</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.OutPut.Phase2.ApparentPower</name>
        <registerIndex>308</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.OutPut.Phase3.ApparentPower</name>
        <registerIndex>309</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Total.Output.ActivePower</name>
        <registerIndex>310</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Total.Output.ApparentPower</name>
        <registerIndex>311</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Total.Output.PercentLoad</name>
        <registerIndex>313</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase1.Peak.Factor</name>
        <registerIndex>314</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase2.Peak.Factor</name>
        <registerIndex>315</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase3.Peak.Factor</name>
        <registerIndex>316</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Power.Factor</name>
        <registerIndex>317</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Mains.Input.Frequency</name>
        <registerIndex>318</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Bypass.Input.Frequency</name>
        <registerIndex>320</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Frequency</name>
        <registerIndex>321</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase1.Power.Factor</name>
        <registerIndex>322</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase2.Power.Factor</name>
        <registerIndex>323</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A2</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Output.Phase3.Power.Factor</name>
        <registerIndex>324</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>电池剩余运行时间（分钟）</displayName>-->
        <name>UPS.Battery.Remain.Runtime</name>
        <registerIndex>329</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>电池温度（℃）</displayName>-->
        <name>UPS.Battery.Temperature</name>
        <registerIndex>330</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>电池剩余容量（％）</displayName>-->
        <name>UPS.Battery.Remain.Capacity</name>
        <registerIndex>331</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Mains.Input.Phase1ToNeutral.Voltage</name>
        <registerIndex>336</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Mains.Input.Phase2ToNeutral.Voltage</name>
        <registerIndex>337</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Mains.Input.Phase3ToNeutral.Voltage</name>
        <registerIndex>338</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>电池总数</displayName>-->
        <name>UPS.Total.NumberOfBatteries.Count</name>
        <registerIndex>339</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>电池总容量</displayName>-->
        <name>UPS.Total.Battery.Capacity</name>
        <registerIndex>340</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Battery.Temperature.DebugF</name>
        <registerIndex>341</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.UIO.SensorPort1.Temperature.DegF</name>
        <registerIndex>342</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>UIO传感器端口1最大温度阈值In DegF</displayName>-->
        <name>UPS.UIO.SensorPort1.MaxTemperature.DegF</name>
        <registerIndex>343</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>UIO传感器端口1最小温度阈值 In DegF</displayName>-->
        <name>UPS.UIO.SensorPort1.MinTemperature.DegF</name>
        <registerIndex>344</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.UIO.SensorPort1.Temperature.DegC</name>
        <registerIndex>384</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>UIO传感器端口1最大温度阈值In DegC</displayName>-->
        <name>UPS.UIO.SensorPort1.MaxTemperature.DegC</name>
        <registerIndex>385</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>UIO传感器端口1最小温度阈值 In DegC</displayName>-->
        <name>UPS.UIO.SensorPort1.MinTemperature.DegC</name>
        <registerIndex>388</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.UIO.SensorPort1.Humidity</name>
        <registerIndex>391</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>UIO传感器端口1最大湿度阈值</displayName>-->
        <name>UPS.UIO.SensorPort1.MaxHumidity</name>
        <registerIndex>392</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>UIO传感器端口1最小湿度阈值</displayName>-->
        <name>UPS.UIO.SensorPort1.MinHumidity</name>
        <registerIndex>395</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A3</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Nominal.Output.ApparentPower</name>
        <registerIndex>521</registerIndex>
        <scale>2</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A4</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName></displayName>-->
        <name>UPS.Number.In.Parallel.Installation</name>
        <registerIndex>529</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A4</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>标称电池备用时间(分钟)</displayName>-->
        <name>UPS.Nominal.Battery.Backup.Time</name>
        <registerIndex>530</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A4</commandName>
        <divider>1.0</divider>
      </SensorDefine>
      <SensorDefine>
        <#--<displayName>标称电池电压</displayName>-->
        <name>UPS.Nominal.Battery.Voltage</name>
        <registerIndex>531</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>Modbus_MGE_Galaxy300_${object.index}_A4</commandName>
        <divider>1.0</divider>
      </SensorDefine>
    </iSensorDefines>
  </DeviceDefine>
</#list>
</linked-list>