<list>
    <#list cabinets as cabinet>
    <CabinetComponentV2>
        <deviceId>device_cabinet${cabinet.index}</deviceId>
        <datas>
            <Sensor>
                <id>1</id>
                <displayName>temperature_1</displayName>
                <deviceId>${cabinet.pduA.uuid}</deviceId>
                <sensorId>PDU_Temperature</sensorId>
            </Sensor>
            <Sensor>
                <id>2</id>
                <displayName>temperature_2</displayName>
                <deviceId>${cabinet.pduB.uuid}</deviceId>
                <sensorId>PDU_Temperature</sensorId>
            </Sensor>
            <Sensor>
                <id>3</id>
                <displayName>humidity_1</displayName>
                <deviceId>${cabinet.pduA.uuid}</deviceId>
                <sensorId>PDU_Humidity</sensorId>
            </Sensor>
            <Sensor>
                <id>4</id>
                <displayName>humidity_2</displayName>
                <deviceId>${cabinet.pduB.uuid}</deviceId>
                <sensorId>PDU_Humidity</sensorId>
            </Sensor>
            <Sensor>
                <id>5</id>
                <displayName>机柜温度(℃)</displayName>
                <deviceId>${cabinet.emh.deviceid}</deviceId>
                <sensorId>THADA.1.Tempture</sensorId>
            </Sensor>
        </datas>
        <sensors>
            <Sensor>
                <id>1</id>
                <displayName>PDU${cabinet.index}-A温度(℃)</displayName>
                <deviceId>${cabinet.pduA.uuid}</deviceId>
                <sensorId>PDU_Temperature</sensorId>
            </Sensor>
            <Sensor>
                <id>2</id>
                <displayName>PDU${cabinet.index}-B温度(℃)</displayName>
                <deviceId>${cabinet.pduB.uuid}</deviceId>
                <sensorId>PDU_Temperature</sensorId>
            </Sensor>
            <Sensor>
                <id>3</id>
                <displayName>PDU${cabinet.index}-A湿度(%)</displayName>
                <deviceId>${cabinet.pduA.uuid}</deviceId>
                <sensorId>PDU_Humidity</sensorId>
            </Sensor>
            <Sensor>
                <id>4</id>
                <displayName>PDU${cabinet.index}-B湿度(%)</displayName>
                <deviceId>${cabinet.pduB.uuid}</deviceId>
                <sensorId>PDU_Humidity</sensorId>
            </Sensor>
            <Sensor>
                <id>5</id>
                <displayName>机柜温度(℃)</displayName>
                <deviceId>${cabinet.emh.deviceid}</deviceId>
                <sensorId>THADA.1.Tempture</sensorId>
            </Sensor>
        </sensors>
        <alertEntries>
            <AlertEntry>
                <deviceId>${cabinet.pduA.uuid}</deviceId>
                <alertId></alertId>
            </AlertEntry>
            <AlertEntry>
                <deviceId>${cabinet.pduB.uuid}</deviceId>
                <alertId></alertId>
            </AlertEntry>
            <AlertEntry>
                <deviceId>${cabinet.emh.deviceid}</deviceId>
                <alertId></alertId>
            </AlertEntry>
            <AlertEntry>
                <deviceId>${cabinet.assertId}</deviceId>
                <alertId></alertId>
            </AlertEntry>
        </alertEntries>
        <uId>${cabinet.assertId}</uId>
        <assertId>${cabinet.assertId}</assertId>
    </CabinetComponentV2>
    </#list>
</list>