<#list list as item>
<SnmpDeviceTable>
    <oid>1.3.6.1.4.1.0.1.2.5.${item.index}.1</oid>
    <type>com.keydak.snmp.table.PdcBranchElectricMOTable</type>
    <deviceIds>
        <string>9cf43f07-e1ed-40ed-9d6e-ce30dd8601b6</string>
    </deviceIds>
    <properties>
        <SnmpDeviceProperty>
            <index>1</index>
            <name>PDC.C${item.branch}.B1.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>2</index>
            <name>PDC.C${item.branch}.B2.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>3</index>
            <name>PDC.C${item.branch}.B3.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>4</index>
            <name>PDC.C${item.branch}.B4.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>5</index>
            <name>PDC.C${item.branch}.B5.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>6</index>
            <name>PDC.C${item.branch}.B6.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>7</index>
            <name>PDC.C${item.branch}.B7.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>8</index>
            <name>PDC.C${item.branch}.B8.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>9</index>
            <name>PDC.C${item.branch}.B9.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>10</index>
            <name>PDC.C${item.branch}.B10.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>11</index>
            <name>PDC.C${item.branch}.B11.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>12</index>
            <name>PDC.C${item.branch}.B12.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>13</index>
            <name>PDC.C${item.branch}.B13.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>14</index>
            <name>PDC.C${item.branch}.B14.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>15</index>
            <name>PDC.C${item.branch}.B15.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>16</index>
            <name>PDC.C${item.branch}.B16.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>17</index>
            <name>PDC.C${item.branch}.B17.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>18</index>
            <name>PDC.C${item.branch}.B18.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>19</index>
            <name>PDC.C${item.branch}.B19.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>20</index>
            <name>PDC.C${item.branch}.B20.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>21</index>
            <name>PDC.C${item.branch}.B21.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>22</index>
            <name>PDC.C${item.branch}.B22.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>23</index>
            <name>PDC.C${item.branch}.B23.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>24</index>
            <name>PDC.C${item.branch}.B24.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>25</index>
            <name>PDC.C${item.branch}.B25.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>26</index>
            <name>PDC.C${item.branch}.B26.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>27</index>
            <name>PDC.C${item.branch}.B27.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>28</index>
            <name>PDC.C${item.branch}.B28.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>29</index>
            <name>PDC.C${item.branch}.B29.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>30</index>
            <name>PDC.C${item.branch}.B30.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>31</index>
            <name>PDC.C${item.branch}.B31.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>32</index>
            <name>PDC.C${item.branch}.B32.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>33</index>
            <name>PDC.C${item.branch}.B33.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>34</index>
            <name>PDC.C${item.branch}.B34.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>35</index>
            <name>PDC.C${item.branch}.B35.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>36</index>
            <name>PDC.C${item.branch}.B36.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>37</index>
            <name>PDC.C${item.branch}.B37.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>38</index>
            <name>PDC.C${item.branch}.B38.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>39</index>
            <name>PDC.C${item.branch}.B39.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>40</index>
            <name>PDC.C${item.branch}.B40.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>41</index>
            <name>PDC.C${item.branch}.B41.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>42</index>
            <name>PDC.C${item.branch}.B42.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>43</index>
            <name>PDC.C${item.branch}.B43.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>44</index>
            <name>PDC.C${item.branch}.B44.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>45</index>
            <name>PDC.C${item.branch}.B45.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>46</index>
            <name>PDC.C${item.branch}.B46.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>47</index>
            <name>PDC.C${item.branch}.B47.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
        <SnmpDeviceProperty>
            <index>48</index>
            <name>PDC.C${item.branch}.B48.${item.name}</name>
            <isState>false</isState>
        </SnmpDeviceProperty>
    </properties>
</SnmpDeviceTable>
</#list>