<linked-list>
<#list acrdList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SnmpSensorDefine>
                <name>CRAC.Module.1.SupplyAir.Temperature</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.9</oid>
                <divider>10</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Module.1.ReturnAir.Temperature</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.13</oid>
                <divider>10</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Module.1.ReturnAir.Humidity</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.15</oid>
                <divider>10</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>

            <SnmpSensorDefine>
                <name>CRAC.Superheat</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.46</oid>
                <divider>10</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Fan.RPM</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.48</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Compressor.Speed</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.49</oid>
                <divider>10</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Unit.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.55</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.AirFilter.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.56</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Compressor.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.57</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.CondenserFan.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.58</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.CondensatePump.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.59</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Fan.1.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.60</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Fan.2.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.61</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Fan.3.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.62</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Fan.4.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.63</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Fan.5.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.64</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Fan.6.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.65</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Fan.7.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.66</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
            <SnmpSensorDefine>
                <name>CRAC.Fan.8.Runtime</name>
                <commandName>crac_acrd_D${object.index}_snmp1</commandName>
                <oid>.1.3.6.1.4.1.318.1.1.27.1.4.1.2.1.3.67</oid>
                <divider>1</divider>
                <precision>1</precision>
                <isMean>false</isMean>
            </SnmpSensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>