#Value注解
name: homkey
password: 123456
syscontent: "name:${name},password:${password}"
student:
  name: studentName
  age: 18
#Swagger2
swagger:
  enabled: true
server:
  port: 8088
  servlet:
    context-path: /
#spring
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #?useSSL=false
    url: jdbc:mysql://193.112.139.155:3306/springboot-mvn?characterEncoding=utf8&useSSL=false
    username: talent
    password: 123456
    #以下都是druid连接池配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j2
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3600
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    #lettuce客户端
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8
      shutdown-timeout: 100ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    # 这个是配置模板路径的，默认就是templates，可不用配置
    prefix: classpath:/templates/
    # 这个可以不配置，检查模板位置
    check-template-location: true
    # 下面3个不做解释了，可以不配置
    # suffix: .html
    # encoding: UTF-8
    # content-type: text/html
    # 模板的模式
    mode: LEGACYHTML5
#mybatis
mybatis-plus:
  mapper-locations: classpath*:resources/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hk.base.entity
  #枚举转换 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.hk.demo.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: com.hk.base.interceptor.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    #jdbc-type-for-null: 'null'
logging:
  level:
    root: info
