<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<linked-list>
  <DeviceDefine>
    <deviceId>${deviceId}</deviceId>
    <iSensorDefines>
      <SensorDefine>
        <name>CRAC.A.Voltage</name>
        <registerIndex>23</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.B.Voltage</name>
        <registerIndex>24</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.C.Voltage</name>
        <registerIndex>25</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Frequency</name>
        <registerIndex>26</registerIndex>
        <scale>1</scale>
        <isMean>false</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      
      <!--<SensorDefine>
        <name>CRAC.State.SoftShutDown</name>
        <isState>true</isState>
        <registerIndex>23</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.LocalShutDown</name>
        <isState>true</isState>
        <registerIndex>69</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.MonitorShutDown</name>
        <isState>true</isState>
        <registerIndex>70</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.RemoteShutDown</name>
        <isState>true</isState>
        <registerIndex>71</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Refrig</name>
        <isState>true</isState>
        <registerIndex>81</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Heat</name>
        <isState>true</isState>
        <registerIndex>82</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Humid</name>
        <isState>true</isState>
        <registerIndex>83</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Dehumid</name>
        <isState>true</isState>
        <registerIndex>84</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Fan1</name>
        <isState>true</isState>
        <registerIndex>73</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Fan2</name>
        <isState>true</isState>
        <registerIndex>74</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Fan3</name>
        <isState>true</isState>
        <registerIndex>75</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.Fan4</name>
        <isState>true</isState>
        <registerIndex>76</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.PumpOutput</name>
        <isState>true</isState>
        <registerIndex>12</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.CompressorOutput</name>
        <isState>true</isState>
        <registerIndex>13</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.HeaterOutput</name>
        <isState>true</isState>
        <registerIndex>14</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.FanOutput</name>
        <isState>true</isState>
        <registerIndex>15</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.HumidOutput</name>
        <isState>true</isState>
        <registerIndex>16</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.State.CommonAlarmOutput</name>
        <isState>true</isState>
        <registerIndex>17</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.HighPressure</name>
        <registerIndex>24</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.LowPressure</name>
        <registerIndex>25</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.ReturnAir.Temperature.Over</name>
        <registerIndex>29</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.OutAir.Temperature.Less</name>
        <registerIndex>30</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.OutAir.Temperature.Over</name>
        <registerIndex>31</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.ReturnAir.Humidity.Over</name>
        <registerIndex>32</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alert.ReturnAir.Humidity.Less</name>
        <registerIndex>33</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.Flood</name>
        <registerIndex>42</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.Alarm.FilterClog</name>
        <registerIndex>44</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q1_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>-->

      <SensorDefine>
        <name>CRAC.ReturnAir.Temperature1</name>
        <registerIndex>30</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.ReturnAir.Temperature2</name>
        <registerIndex>31</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.ReturnAir.Temperature3</name>
        <registerIndex>32</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.ReturnAir.Humidity1</name>
        <registerIndex>33</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.ReturnAir.Humidity2</name>
        <registerIndex>34</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.ReturnAir.Humidity3</name>
        <registerIndex>35</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.OutAir.Temperature1</name>
        <registerIndex>36</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q3_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.OutAir.Temperature2</name>
        <registerIndex>37</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q3_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.OutAir.Temperature3</name>
        <registerIndex>38</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q3_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.OutAir.Humidity1</name>
        <registerIndex>39</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q3_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.OutAir.Humidity2</name>
        <registerIndex>40</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q3_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.OutAir.Humidity3</name>
        <registerIndex>41</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q3_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      
      <!--<SensorDefine>
        <name>CRAC.Switch.State</name>
        <isState>true</isState>
        <registerIndex>63</registerIndex>
        <scale>0</scale>
        <isMean>false</isMean>
        <commandName>crac_q4_${deviceId}_A1</commandName>
        <divider>1</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.OutAir.Temperature</name>
        <registerIndex>1</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>
      <SensorDefine>
        <name>CRAC.ReturnAir.Humidity</name>
        <registerIndex>10</registerIndex>
        <scale>1</scale>
        <isMean>true</isMean>
        <commandName>crac_q2_${deviceId}_A1</commandName>
        <divider>10</divider>
      </SensorDefine>-->
     
    </iSensorDefines>
  </DeviceDefine>
</linked-list>
