<?xml version="1.0" encoding="UTF-8"?>

<linked-list> 
  <DeviceDefine> 
    <deviceId>${deviceId}</deviceId>
    <iSensorDefines> 
      <SensorDefine> 
        <name>EMH.1.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>8</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>9</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>10</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>11</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>12</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>13</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>14</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>15</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>16</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>17</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>18</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>19</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>20</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>21</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>22</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>23</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>24</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>25</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>26</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>27</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>28</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>29</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>30</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>31</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>32</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>33</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>34</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>35</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>36</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>37</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>38</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>39</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>40</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>41</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>42</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>43</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>44</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>45</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>46</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>47</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>48</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>49</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>50</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>51</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>52</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>53</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>54</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>55</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>56</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>57</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>58</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>59</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>60</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>61</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>62</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>63</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>64</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>65</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>66</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>67</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>68</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>69</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>70</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>71</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>72</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>73</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>74</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>75</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>76</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>77</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>78</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>79</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>80</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>81</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>82</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>83</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>84</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>85</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>86</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>87</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>88</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>89</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>90</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>91</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>92</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>93</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>94</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>95</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>96</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>97</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>98</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>99</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>100</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>101</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>102</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>103</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>104</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>105</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Magnetometer.Access.State</name>  
        <isState>true</isState>
        <registerIndex>106</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Smoke.Access.State</name>  
        <isState>true</isState>
        <registerIndex>107</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.TH.Access.State</name>  
        <isState>true</isState>
        <registerIndex>108</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Magnetometer.State</name>  
        <isState>true</isState>
        <registerIndex>109</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Smoke.State</name>  
        <isState>true</isState>
        <registerIndex>110</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Magnetometer.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>111</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Magnetometer.Connect.State</name>  
        <isState>true</isState>
        <registerIndex>112</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Pressure.Access.State</name>  
        <isState>true</isState>
        <registerIndex>113</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Pressure.Access.State</name>  
        <isState>true</isState>
        <registerIndex>114</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Pressure.Access.State</name>  
        <isState>true</isState>
        <registerIndex>115</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Pressure.Access.State</name>  
        <isState>true</isState>
        <registerIndex>116</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Pressure.Access.State</name>  
        <isState>true</isState>
        <registerIndex>117</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Unit.PowerSupply.State</name>  
        <isState>true</isState>
        <registerIndex>118</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q1_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Critial.Stop</name>  
        <registerIndex>119</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Fire.Open</name>  
        <registerIndex>120</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Fire.Close</name>  
        <registerIndex>121</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.All</name>  
        <registerIndex>122</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Temperature.Over</name>  
        <registerIndex>123</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Temperature.Less</name>  
        <registerIndex>124</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Humidity.Over</name>  
        <registerIndex>125</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Humidity.Less</name>  
        <registerIndex>126</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Smoke</name>  
        <registerIndex>127</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Water</name>  
        <registerIndex>128</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Magnetometer</name>  
        <registerIndex>129</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Critial.Stop</name>  
        <registerIndex>130</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Fire.Open</name>  
        <registerIndex>131</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Fire.Close</name>  
        <registerIndex>132</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Alert.Pressure</name>  
        <registerIndex>133</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Alert.Temperature.Over</name>  
        <registerIndex>134</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Alert.Temperature.Over</name>  
        <registerIndex>135</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Alert.Temperature.Over</name>  
        <registerIndex>136</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Alert.Temperature.Over</name>  
        <registerIndex>137</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Alert.Temperature.Over</name>  
        <registerIndex>138</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Alert.Temperature.Over</name>  
        <registerIndex>139</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Alert.Temperature.Over</name>  
        <registerIndex>140</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Alert.Temperature.Over</name>  
        <registerIndex>141</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Alert.Temperature.Over</name>  
        <registerIndex>142</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Alert.Temperature.Over</name>  
        <registerIndex>143</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Alert.Temperature.Over</name>  
        <registerIndex>144</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Alert.Temperature.Over</name>  
        <registerIndex>145</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Alert.Temperature.Over</name>  
        <registerIndex>146</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Alert.Temperature.Over</name>  
        <registerIndex>147</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Alert.Temperature.Over</name>  
        <registerIndex>148</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Alert.Temperature.Less</name>  
        <registerIndex>149</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Alert.Temperature.Less</name>  
        <registerIndex>150</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Alert.Temperature.Less</name>  
        <registerIndex>151</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Alert.Temperature.Less</name>  
        <registerIndex>152</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Alert.Temperature.Less</name>  
        <registerIndex>153</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Alert.Temperature.Less</name>  
        <registerIndex>154</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Alert.Temperature.Less</name>  
        <registerIndex>155</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Alert.Temperature.Less</name>  
        <registerIndex>156</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Alert.Temperature.Less</name>  
        <registerIndex>157</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Alert.Temperature.Less</name>  
        <registerIndex>158</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Alert.Temperature.Less</name>  
        <registerIndex>159</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Alert.Temperature.Less</name>  
        <registerIndex>160</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Alert.Temperature.Less</name>  
        <registerIndex>161</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Alert.Temperature.Less</name>  
        <registerIndex>162</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Alert.Temperature.Less</name>  
        <registerIndex>163</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Alert.Temperature.Over</name>  
        <registerIndex>164</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Alert.Temperature.Over</name>  
        <registerIndex>165</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Alert.Temperature.Over</name>  
        <registerIndex>166</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Alert.Temperature.Over</name>  
        <registerIndex>167</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Alert.Temperature.Over</name>  
        <registerIndex>168</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Alert.Temperature.Over</name>  
        <registerIndex>169</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Alert.Temperature.Over</name>  
        <registerIndex>170</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Alert.Temperature.Over</name>  
        <registerIndex>171</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Alert.Temperature.Over</name>  
        <registerIndex>172</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Alert.Temperature.Over</name>  
        <registerIndex>173</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Alert.Temperature.Over</name>  
        <registerIndex>174</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Alert.Temperature.Over</name>  
        <registerIndex>175</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Alert.Temperature.Over</name>  
        <registerIndex>176</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Alert.Temperature.Over</name>  
        <registerIndex>177</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Alert.Temperature.Over</name>  
        <registerIndex>178</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Alert.Temperature.Less</name>  
        <registerIndex>179</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Alert.Temperature.Less</name>  
        <registerIndex>180</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Alert.Temperature.Less</name>  
        <registerIndex>181</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Alert.Temperature.Less</name>  
        <registerIndex>182</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Alert.Temperature.Less</name>  
        <registerIndex>183</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Alert.Temperature.Less</name>  
        <registerIndex>184</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Alert.Temperature.Less</name>  
        <registerIndex>185</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Alert.Temperature.Less</name>  
        <registerIndex>186</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Alert.Temperature.Less</name>  
        <registerIndex>187</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Alert.Temperature.Less</name>  
        <registerIndex>188</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Alert.Temperature.Less</name>  
        <registerIndex>189</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Alert.Temperature.Less</name>  
        <registerIndex>190</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Alert.Temperature.Less</name>  
        <registerIndex>191</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Alert.Temperature.Less</name>  
        <registerIndex>192</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Alert.Temperature.Less</name>  
        <registerIndex>193</registerIndex>  
        <scale>0</scale>  
        <isMean>false</isMean>  
        <commandName>emh_q2_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Tempture</name>  
        <registerIndex>8</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.1.Humidity</name>  
        <registerIndex>9</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Tempture</name>  
        <registerIndex>10</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.2.Humidity</name>  
        <registerIndex>11</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Tempture</name>  
        <registerIndex>12</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.3.Humidity</name>  
        <registerIndex>13</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Tempture</name>  
        <registerIndex>14</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.4.Humidity</name>  
        <registerIndex>15</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Tempture</name>  
        <registerIndex>16</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.5.Humidity</name>  
        <registerIndex>17</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Tempture</name>  
        <registerIndex>18</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.6.Humidity</name>  
        <registerIndex>19</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Tempture</name>  
        <registerIndex>20</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.7.Humidity</name>  
        <registerIndex>21</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Tempture</name>  
        <registerIndex>22</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.8.Humidity</name>  
        <registerIndex>23</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Tempture</name>  
        <registerIndex>24</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.9.Humidity</name>  
        <registerIndex>25</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Tempture</name>  
        <registerIndex>26</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.10.Humidity</name>  
        <registerIndex>27</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Tempture</name>  
        <registerIndex>28</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.11.Humidity</name>  
        <registerIndex>29</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Tempture</name>  
        <registerIndex>30</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.12.Humidity</name>  
        <registerIndex>31</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Tempture</name>  
        <registerIndex>32</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.13.Humidity</name>  
        <registerIndex>33</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Tempture</name>  
        <registerIndex>34</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.14.Humidity</name>  
        <registerIndex>35</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Tempture</name>  
        <registerIndex>36</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.15.Humidity</name>  
        <registerIndex>37</registerIndex>  
        <scale>2</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>100</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Pressure.1</name>  
        <registerIndex>38</registerIndex>  
        <scale>0</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Pressure.2</name>  
        <registerIndex>39</registerIndex>  
        <scale>0</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Pressure.3</name>  
        <registerIndex>40</registerIndex>  
        <scale>0</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine>  
      <SensorDefine> 
        <name>EMH.Pressure.4</name>  
        <registerIndex>41</registerIndex>  
        <scale>0</scale>  
        <isMean>true</isMean>  
        <commandName>emh_q3_${deviceId}_A1</commandName>
        <divider>1</divider> 
      </SensorDefine> 
    </iSensorDefines> 
  </DeviceDefine> 
</linked-list>
