package com.hk.freemarker.keydak.conf;

/**
 * Created by LuHj on 2018/10/18.
 */
public class GhgsConfig {

    public static String[] UPS_DEVICES = new String[]{
            "1|UPS.Bypass.A.Voltage|1|10|false|旁路电压A",
            "2|UPS.Bypass.B.Voltage|1|10|false|旁路电压B",
            "3|UPS.Bypass.C.Voltage|1|10|false|旁路电压C",
            "4|UPS.Bypass.A.Current|1|10|false|旁路电流A",
            "5|UPS.Bypass.B.Current|1|10|false|旁路电流B",
            "6|UPS.Bypass.C.Current|1|10|false|旁路电流C",
            "7|UPS.Bypass.A.Frequency|2|100|false|旁路频率A",
            "8|UPS.Bypass.B.Frequency|2|100|false|旁路频率B",
            "9|UPS.Bypass.C.Frequency|2|100|false|旁路频率C",
            "10|UPS.Bypass.A.Factor|2|100|false|旁路功率因子A",
            "11|UPS.Bypass.B.Factor|2|100|false|旁路功率因子B",
            "12|UPS.Bypass.C.Factor|2|100|false|旁路功率因子C",
            "13|UPS.Input.A.Voltage|1|10|false|输入电压A",
            "14|UPS.Input.B.Voltage|1|10|false|输入电压B",
            "15|UPS.Input.C.Voltage|1|10|false|输入电压C",
            "16|UPS.Input.A.Current|1|10|false|输入电流A",
            "17|UPS.Input.B.Current|1|10|false|输入电流B",
            "18|UPS.Input.C.Current|1|10|false|输入电流C",
            "19|UPS.Input.A.Frequency|2|100|false|输入频率A",
            "20|UPS.Input.B.Frequency|2|100|false|输入频率B",
            "21|UPS.Input.C.Frequency|2|100|false|输入频率C",
            "22|UPS.Input.A.Factor|2|100|false|输入功率因子A",
            "23|UPS.Input.B.Factor|2|100|false|输入功率因子B",
            "24|UPS.Input.C.Factor|2|100|false|输入功率因子C",
            "25|UPS.Output.A.Voltage|1|10|false|输出电压A",
            "26|UPS.Output.B.Voltage|1|10|false|输出电压B",
            "27|UPS.Output.C.Voltage|1|10|false|输出电压C",
            "28|UPS.Output.A.Current|1|10|false|输出电流A",
            "29|UPS.Output.B.Current|1|10|false|输出电流B",
            "30|UPS.Output.C.Current|1|10|false|输出电流C",
            "31|UPS.Output.A.Frequency|2|100|false|输出频率A",
            "32|UPS.Output.B.Frequency|2|100|false|输出频率B",
            "33|UPS.Output.C.Frequency|2|100|false|输出频率C",
            "34|UPS.Output.A.Factor|2|100|false|输出功率因子A",
            "35|UPS.Output.B.Factor|2|100|false|输出功率因子B",
            "36|UPS.Output.C.Factor|2|100|false|输出功率因子C",
            "37|UPS.Output.A.ApparentPower|1|10|false|输出在视功率A",
            "38|UPS.Output.B.ApparentPower|1|10|false|输出在视功率B",
            "39|UPS.Output.C.ApparentPower|1|10|false|输出在视功率C",
            "40|UPS.Output.A.ActivePower|1|10|false|输出有功功率A",
            "41|UPS.Output.B.ActivePower|1|10|false|输出有功功率B",
            "42|UPS.Output.C.ActivePower|1|10|false|输出有功功率C",
            "43|UPS.Output.A.ReactivePower|1|10|false|输出无功功率A",
            "44|UPS.Output.B.ReactivePower|1|10|false|输出无功功率B",
            "45|UPS.Output.C.ReactivePower|1|10|false|输出无功功率C",
            "46|UPS.Output.A.PercentLoad|1|10|false|输出负载A",
            "47|UPS.Output.B.PercentLoad|1|10|false|输出负载B",
            "48|UPS.Output.C.PercentLoad|1|10|false|输出负载C",
            "49|UPS.Env.Temperature|1|10|false|环境温度",
            "50|UPS.Battery.Positive.Voltage|1|10|false|电池正极电压",
            "51|UPS.Battery.Negative.Voltage|1|10|false|电池负极电压",
            "52|UPS.Battery.Positive.Current|1|10|false|电池正极电流",
            "53|UPS.Battery.Negative.Current|1|10|false|电池负极电流",
            "54|UPS.Battery.Temperature|1|10|false|电池温度",
            "55|UPS.Battery.ReserveTime|1|10|false|电池剩余时间",
            "56|UPS.Battery.ReserveCapacity|1|10|false|电池剩余容量",
            //q2
            "81|UPS.Alert.Supply|0|1|false|供电方式:0均不供电,1UPS供电,2旁路供电|0=均不供电告警:2=旁路供电告警",
            "82|UPS.State.Battery|0|1|false|电池状态:0电池未工作,1电池浮充,2电池均充,3电池放电",
            "83|UPS.State.Battery.Connection|0|1|false|电池连接状态:0未连接,1已连接",
            "84|UPS.State.Bypass.Repair|0|1|false|维修旁路空开状态:0断开,1闭合",
            "85|UPS.State.EPO|0|1|false|EPO:0无紧急关机,1紧急关机",
            "86|UPS.State.Inverter.Capacity|0|1|false|逆变器启动容量不足:0正常,1异常",
            "87|UPS.State.Generator|0|1|false|发电机接入:0断开,1接入",
            "88|UPS.Alert.Input.Current|0|1|false|交流输入故障:0正常,1故障|1=告警",
            "89|UPS.Alert.Bypass.Phase|0|1|false|旁路相序故障:0正常,1故障|1=告警",
            "90|UPS.Alert.Bypass.Voltage|0|1|false|旁路电压故障:0正常,1故障|1=告警",
            "91|UPS.Alert.Bypass|0|1|false|旁路故障:0正常,1故障|1=告警",
            "92|UPS.Alert.Bypass.Overload|0|1|false|旁路过载故障:0未过载,1过载|1=告警",
            "93|UPS.Alert.Bypass.Overtime|0|1|false|旁路过载超时:0正常,1过载超时|1=告警",
            "94|UPS.Alert.Bypass.SuperTracking|0|1|false|旁路超跟踪:0正常,1旁路超跟踪|1=告警",
            "95|UPS.Alert.ChangeCount|0|1|false|切换次数到:0次数未到,1次数到|1=告警",
            "96|UPS.Alert.Output.Short|0|1|false|输出短路:0正常,1故障|1=告警",
            "97|UPS.Alert.Battery.EOD|0|1|false|电池EOD:0未EOD,1电池EOD|1=告警",
//            "98|UPS.State.Battery.Test|0|1|false|X电池测试:0无电池测试,1电池测试",
            "99|UPS.State.Battery.Test.Self|0|1|false|电池自检状态:0未自检,1成功,2失败,3自检中",
//            "100|UPS.State.Battery.Test.Hand|0|1|false|电池手动测试:0正常,1故障",
            "101|UPS.State.Battery.Maintain|0|1|false|电池维护状态:0为维护测试,1成功,2失败,3维护测试中",
            "107|UPS.Alert.Battery.Voltage.Low|0|1|false|电池低压:0电池未低压,1电池低压|1=告警",
            "108|UPS.Alert.Battery.Inversion|0|1|false|电池接反:0电池未接反,1电池接反|1=告警",
            "109|UPS.Alert.Rectifier|0|1|false|整流器状态:0 OFF,1 SoftStart,2NormalWork|0=OFF:1=SoftStart",
            "110|UPS.State.Input.N|0|1|false|输入N线断开:0未断开,1断开|1=告警",
            "111|UPS.Alert.Bypass.Fan|0|1|false|旁路风扇:0正常,1故障|1=故障告警",
            "112|UPS.State.NX|0|1|false|失去 N+X 冗余:0未失去 1失去",
            "113|UPS.State.EOD|0|1|false|EOD 系统禁止:0未禁止 1禁止",
            "114|UPS.Alert.CT|0|1|false|CT焊反:0正常 1焊反|1=故障告警"
    };
    public static String[][] AC_DEVICES_SWITCH = new String[][]{
        new String[]{
                "1|0|AC.Switch|开关机状态(0:关机状态,1:开机状态)|0=关机告警",
                "1|1|AC.FanState|风机(0:关闭状态,1:开启状态)|0=关闭告警",
                "1|2|AC.HeatingState|制热(0:非制热状态,1:制热状态)",
                "1|3|AC.CoolingState|制冷(0:非制冷状态,1:制冷状态)",
                "1|4|AC.HumidificationState|加湿(0:非加湿状态,1:加湿状态)",
                "1|5|AC.DehumidificationState|除湿(0:非除湿状态,1:除湿状态)",
                "1|8|AC.GroupControl|群控模式(0:单机状态,1:群控状态)"
        },
        new String[]{
                "4|0|AC.Alert.ReturnAirHighTemperature|回风高温|1=告警",
                "4|1|AC.Alert.ReturnAirLowTemperature|回风低温|1=告警",
                "4|2|AC.Alert.ReturnAirHighHumidity|回风高湿|1=告警",
                "4|3|AC.Alert.ReturnAirLowHumidity|回风低湿|1=告警",
                "4|4|AC.Alert.SupplyAirHighTemperature|送风高温|1=告警",
                "4|5|AC.Alert.SupplyAirLowTemperature|送风高温|1=告警",
                "4|8|AC.Alert.HardwareProbeFailed|Modbus 硬件故障(温湿度板、电源板硬件故障)|1=告警",
                "4|9|AC.Alert.CommunicationProbeFailed|Modbus 通信故障(温湿度板、电源板通信故障)|1=告警",
                "4|11|AC.Alert.FanProbeFailed|风机故障|1=告警"
        },
        new String[]{
                "5|1|AC.Alert.FanOvertime|风机超时|1=告警",
                "5|7|AC.Alert.Compressor.1.HighPressure|压机1高压|1=告警",
                "5|8|AC.Alert.Compressor.1.HighPressure.Lock|压机1高压锁死|1=告警",
                "5|9|AC.Alert.Compressor.1.LowPressure|压机1低压|1=告警",
                "5|10|AC.Alert.Compressor.1.LowPressure.Lock|压机1低压锁死|1=告警",
                "5|13|AC.Alert.Compressor.1.ShortPeriod|压机1短周期|1=告警",
                "5|14|AC.Alert.Compressor.1.Overtime|压机1超时|1=告警",
                "5|15|AC.Alert.Compressor.2.HighPressure|压机2高压|1=告警"
        },
        new String[]{
                "6|1|AC.Alert.FanOvertime|风机超时|1=告警",
                "6|7|AC.Alert.Compressor.1.HighPressure|压机1高压|1=告警",
                "6|8|AC.Alert.Compressor.1.HighPressure.Lock|压机1高压锁死|1=告警",
                "6|9|AC.Alert.Compressor.1.LowPressure|压机1低压|1=告警",
                "6|10|AC.Alert.Compressor.1.LowPressure.Lock|压机1低压锁死|1=告警",
                "6|13|AC.Alert.Compressor.1.ShortPeriod|压机1短周期|1=告警",
                "6|14|AC.Alert.Compressor.1.Overtime|压机1超时|1=告警",
                "6|15|AC.Alert.Compressor.2.HighPressure|压机2高压|1=告警"
        },
        new String[]{
                "7|0|AC.Alert.Compressor.2.HighPressure.Lock|压机2高压锁死|1=告警",
                "7|1|AC.Alert.Compressor.2.LowPressure|压机2低压|1=告警",
                "7|2|AC.Alert.Compressor.2.LowPressure.Lock|压机2低压锁死|1=告警",
                "7|5|AC.Alert.Compressor.2.ShortPeriod|压机2短周期|1=告警",
                "7|6|AC.Alert.Compressor.2.Overtime|压机2超时|1=告警",
                "7|7|AC.Alert.Humidifier.Current.TooLarge|加湿器大电流|1=告警",
                "7|9|AC.Alert.Humidifier.WaterShortage|加湿器干烧|1=告警",
                "7|10|AC.Alert.Humidifier.Overtime|加湿器超时|1=告警",
                "7|11|AC.Alert.Heater.Overload|加湿器过载|1=告警",
                "7|12|AC.Alert.Heater.1.Overtime|加湿器1超时|1=告警",
                "7|13|AC.Alert.Heater.2.Overtime|加湿器2超时|1=告警",
                "7|14|AC.Alert.PowerOff|掉电|1=告警",
                "7|15|AC.Alert.PhaseSequence|相序错误|1=告警"
        },
        new String[]{
                "8|0|AC.Alert.PowerFrequency.High|电源频率偏高|1=告警",
                "8|1|AC.Alert.PowerFrequency.Low|电源频率偏低|1=告警",
                "8|2|AC.Alert.A.Voltage.Over|A相过压|1=告警",
                "8|3|AC.Alert.B.Voltage.Over|B相过压|1=告警",
                "8|4|AC.Alert.C.Voltage.Over|C相过压|1=告警",
                "8|5|AC.Alert.A.Voltage.Under|A相欠压|1=告警",
                "8|6|AC.Alert.B.Voltage.Under|B相欠压|1=告警",
                "8|7|AC.Alert.C.Voltage.Under|C相欠压|1=告警",
                "8|8|AC.Alert.A.Deficiency|A相缺相|1=告警",
                "8|9|AC.Alert.B.Deficiency|B相缺相|1=告警",
                "8|10|AC.Alert.C.Deficiency|C相缺相|1=告警",
                "8|11|AC.Alert.Air.Loss|气流丢失|1=告警",
                "8|12|AC.Alert.AirFilter.Overtime|过滤网超时|1=告警",
                "8|13|AC.Alert.AirFilter.Block|过滤网堵塞|1=告警",
                "8|14|AC.Alert.Remote.Shutdown|远程关机|1=告警",
                "8|15|AC.Alert.Water.Leakage|漏水告警|1=告警"
        },
        new String[]{
                "9|0|AC.Alert.GroupControl|群控异常|1=告警",
                "9|4|AC.Alert.Smoke|烟雾告警|1=告警"
//                "9|5|AC.Alert.User|自定义告警|1=告警",
        },
        new String[]{
                "10|1|AC.Alert.Humidifier.ProbeFailed|加湿器故障|1=告警",
                "10|3|AC.Alert.Humidifier.Overload|加湿器过载|1=告警",
                "10|8|AC.Alert.Frequency.1.ProbeFailed|泵1变频器故障|1=告警",
                "10|9|AC.Alert.Frequency.2.ProbeFailed|泵2变频器故障|1=告警",
                "10|10|AC.Alert.Frequency.1.Stop|泵1休停|1=告警",
                "10|11|AC.Alert.Voltage.High.Lock|高压降频锁死|1=告警",
                "10|12|AC.Alert.Exhaust.TemperatureHighAlert|排气高温预警|1=告警",
                "10|13|AC.Alert.Exhaust.TemperatureHigh|排气温度高温|1=告警",
                "10|14|AC.Alert.Frequency.2.Stop|泵2休停|1=告警"
        }
    };

}
