<linked-list>
<#list acmList as object>
    <DzRequest>
        <name>crac_acm03u1_dz_d${object.index}_24642_33</name>
        <commandType>24642</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>${object.busId}</addr>
        <ver>33</ver>
        <ctrlData/>
    </DzRequest>
    <DzRequest>
        <name>crac_acm03u1_dz_d${object.index}_24643_33</name>
        <commandType>24643</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>${object.busId}</addr>
        <ver>33</ver>
        <ctrlData/>
    </DzRequest>
    <DzRequest>
        <name>crac_acm03u1_dz_d${object.index}_24706_33</name>
        <commandType>24706</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>${object.busId}</addr>
        <ver>33</ver>
        <ctrlData/>
    </DzRequest>
    <DzRequest>
        <name>crac_acm03u1_dz_d${object.index}_24709_33</name>
        <commandType>24709</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <addr>${object.busId}</addr>
        <ver>33</ver>
        <ctrlData/>
    </DzRequest>
</#list>
</linked-list>