<linked-list>
<#list elmList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ActivePower.A.H</name>
                    <registerIndex>1</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ActivePower.A.L</name>
                    <registerIndex>0</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.A.ActivePower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ActivePower.B.H</name>
                    <registerIndex>3</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ActivePower.B.L</name>
                    <registerIndex>2</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.B.ActivePower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ActivePower.C.H</name>
                    <registerIndex>5</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ActivePower.C.L</name>
                    <registerIndex>4</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.C.ActivePower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ActivePower.All.H</name>
                    <registerIndex>7</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ActivePower.All.L</name>
                    <registerIndex>6</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.ActivePower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ReactivePower.A.H</name>
                    <registerIndex>9</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ReactivePower.A.L</name>
                    <registerIndex>8</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.A.ReactivePower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ReactivePower.B.H</name>
                    <registerIndex>11</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ReactivePower.B.L</name>
                    <registerIndex>10</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.B.ReactivePower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ReactivePower.C.H</name>
                    <registerIndex>13</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ReactivePower.C.L</name>
                    <registerIndex>12</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.C.ReactivePower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ReactivePower.All.H</name>
                    <registerIndex>15</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ReactivePower.All.L</name>
                    <registerIndex>14</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.ReactivePower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ApparentPower.A.H</name>
                    <registerIndex>17</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ApparentPower.A.L</name>
                    <registerIndex>16</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.A.ApparentPower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ApparentPower.B.H</name>
                    <registerIndex>19</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ApparentPower.B.L</name>
                    <registerIndex>18</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.B.ApparentPower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ApparentPower.C.H</name>
                    <registerIndex>21</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ApparentPower.C.L</name>
                    <registerIndex>20</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.C.ApparentPower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ApparentPower.All.H</name>
                    <registerIndex>23</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ApparentPower.All.L</name>
                    <registerIndex>22</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.ApparentPower</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Voltage.A.H</name>
                    <registerIndex>25</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Voltage.A.L</name>
                    <registerIndex>24</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.A.Voltage</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Voltage.B.H</name>
                    <registerIndex>27</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Voltage.B.L</name>
                    <registerIndex>26</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.B.Voltage</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Voltage.C.H</name>
                    <registerIndex>29</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Voltage.C.L</name>
                    <registerIndex>28</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.C.Voltage</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Current.A.H</name>
                    <registerIndex>31</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Current.A.L</name>
                    <registerIndex>30</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.A.Current</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Current.B.H</name>
                    <registerIndex>33</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Current.B.L</name>
                    <registerIndex>32</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.B.Current</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Current.C.H</name>
                    <registerIndex>35</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Current.C.L</name>
                    <registerIndex>34</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.C.Current</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ZeroCurrent.C.H</name>
                    <registerIndex>37</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ZeroCurrent.C.L</name>
                    <registerIndex>36</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.Zero.Current</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.PowerFactor.A.H</name>
                    <registerIndex>39</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.PowerFactor.A.L</name>
                    <registerIndex>38</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.A.PowerFactor</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.PowerFactor.B.H</name>
                    <registerIndex>41</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.PowerFactor.B.L</name>
                    <registerIndex>40</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.B.PowerFactor</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.PowerFactor.C.H</name>
                    <registerIndex>43</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.PowerFactor.C.L</name>
                    <registerIndex>42</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.C.PowerFactor</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.PowerFactor.All.H</name>
                    <registerIndex>45</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.PowerFactor.All.L</name>
                    <registerIndex>44</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.PowerFactor</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Frequency.H</name>
                    <registerIndex>55</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Frequency.L</name>
                    <registerIndex>54</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.Frequency</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.ZeroVoltage.H</name>
                    <registerIndex>57</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ZeroVoltage.L</name>
                    <registerIndex>56</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.Zero.Voltage</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Total.ActivePower.Energy.H</name>
                    <registerIndex>67</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Total.ActivePower.Energy.L</name>
                    <registerIndex>66</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.Active.Energy</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Total.ReactivePower.Energy.H</name>
                    <registerIndex>69</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Total.ReactivePower.Energy.L</name>
                    <registerIndex>68</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.Reactive.Energy</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.Total.ApparentPower.Energy.H</name>
                    <registerIndex>71</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Total.ApparentPower.Energy.L</name>
                    <registerIndex>70</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.Apparent.Energy</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.LineVoltage.AB.H</name>
                    <registerIndex>115</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.LineVoltage.AB.L</name>
                    <registerIndex>114</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.LineVoltage.AB</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.LineVoltage.BC.H</name>
                    <registerIndex>117</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.LineVoltage.BC.L</name>
                    <registerIndex>116</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.LineVoltage.BC</name>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <highPropertyDefines>
                    <name>ELM.LineVoltage.CA.H</name>
                    <registerIndex>119</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.LineVoltage.CA.L</name>
                    <registerIndex>118</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
                <name>ELM.LineVoltage.CA</name>
            </Byte4ToFloatComputeSensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>