<linked-list>
  <DeviceDefine>
    <deviceId>{devid}</deviceId>
    <iSensorDefines>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ActivePower.A.H</name>
          <registerIndex>1</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ActivePower.A.L</name>
          <registerIndex>0</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ActivePower.A</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ActivePower.B.H</name>
          <registerIndex>3</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ActivePower.B.L</name>
          <registerIndex>2</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ActivePower.B</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ActivePower.C.H</name>
          <registerIndex>5</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ActivePower.C.L</name>
          <registerIndex>4</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ActivePower.C</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ActivePower.All.H</name>
          <registerIndex>7</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ActivePower.All.L</name>
          <registerIndex>6</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ActivePower.All</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ReActivePower.A.H</name>
          <registerIndex>9</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ReActivePower.A.L</name>
          <registerIndex>8</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ReActivePower.A</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ReActivePower.B.H</name>
          <registerIndex>11</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ReActivePower.B.L</name>
          <registerIndex>10</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ReActivePower.B</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ReActivePower.C.H</name>
          <registerIndex>13</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ReActivePower.C.L</name>
          <registerIndex>12</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ReActivePower.C</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ReActivePower.All.H</name>
          <registerIndex>15</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ReActivePower.All.L</name>
          <registerIndex>14</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ReActivePower.All</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ApparentPower.A.H</name>
          <registerIndex>17</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ApparentPower.A.L</name>
          <registerIndex>16</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ApparentPower.A</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ApparentPower.B.H</name>
          <registerIndex>19</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ApparentPower.B.L</name>
          <registerIndex>18</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ApparentPower.B</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ApparentPower.C.H</name>
          <registerIndex>21</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ApparentPower.C.L</name>
          <registerIndex>20</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ApparentPower.C</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ApparentPower.All.H</name>
          <registerIndex>23</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ApparentPower.All.L</name>
          <registerIndex>22</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ApparentPower.All</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Voltage.A.H</name>
          <registerIndex>25</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Voltage.A.L</name>
          <registerIndex>24</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Voltage.A</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Voltage.B.H</name>
          <registerIndex>27</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Voltage.B.L</name>
          <registerIndex>26</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Voltage.B</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Voltage.C.H</name>
          <registerIndex>29</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Voltage.C.L</name>
          <registerIndex>28</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Voltage.C</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Current.A.H</name>
          <registerIndex>31</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Current.A.L</name>
          <registerIndex>30</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Current.A</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Current.B.H</name>
          <registerIndex>33</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Current.B.L</name>
          <registerIndex>32</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Current.B</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Current.C.H</name>
          <registerIndex>35</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Current.C.L</name>
          <registerIndex>34</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Current.C</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ZeroCurrent.C.H</name>
          <registerIndex>37</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ZeroCurrent.C.L</name>
          <registerIndex>36</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ZeroCurrent.C</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.PowerFactory.A.H</name>
          <registerIndex>39</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.PowerFactory.A.L</name>
          <registerIndex>38</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.PowerFactory.A</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.PowerFactory.B.H</name>
          <registerIndex>41</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.PowerFactory.B.L</name>
          <registerIndex>40</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.PowerFactory.B</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.PowerFactory.C.H</name>
          <registerIndex>43</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.PowerFactory.C.L</name>
          <registerIndex>42</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.PowerFactory.C</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.PowerFactory.All.H</name>
          <registerIndex>45</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.PowerFactory.All.L</name>
          <registerIndex>44</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_0_45</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.PowerFactory.All</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Frequency.H</name>
          <registerIndex>55</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Frequency.L</name>
          <registerIndex>54</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Frequency</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ZeroVoltage.H</name>
          <registerIndex>57</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ZeroVoltage.L</name>
          <registerIndex>56</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ZeroVoltage</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.AssimilatePower.H</name>
          <registerIndex>59</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.AssimilatePower.L</name>
          <registerIndex>58</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.AssimilatePower</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.ReleasePower.H</name>
          <registerIndex>61</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.ReleasePower.L</name>
          <registerIndex>60</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.ReleasePower</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Inductive.ReActivePower.H</name>
          <registerIndex>63</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Inductive.ReActivePower.L</name>
          <registerIndex>62</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Inductive.ReActivePower</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Capacitive.ReactivePower.H</name>
          <registerIndex>65</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Capacitive.ReactivePowerL</name>
          <registerIndex>64</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Capacitive.ReactivePower</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Total.ActivePower.Energy.H</name>
          <registerIndex>67</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Total.ActivePower.Energy.L</name>
          <registerIndex>66</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Total.ActivePower.Energy</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Total.ReActivePower.Energy.H</name>
          <registerIndex>69</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Total.ReActivePower.Energy.L</name>
          <registerIndex>68</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Total.ReActivePower.Energy</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.Total.ApparentPower.Energy.H</name>
          <registerIndex>71</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.Total.ApparentPower.Energy.L</name>
          <registerIndex>70</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.Total.ApparentPower.Energy</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.UabLine.Voltage.H</name>
          <registerIndex>115</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.UabLine.Voltage.L</name>
          <registerIndex>114</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.UabLine.Voltage</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.UbcLine.Voltage.H</name>
          <registerIndex>117</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.UbcLine.Voltage.L</name>
          <registerIndex>116</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.UbcLine.Voltage</name>
      </Byte4ToFloatComputeSensorDefine>
      <Byte4ToFloatComputeSensorDefine>
        <highPropertyDefines>
          <name>Electrial.UcaLine.Voltage.H</name>
          <registerIndex>119</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </highPropertyDefines>
        <lowPropertyDefines>
          <name>Electrial.UcaLine.Voltage.L</name>
          <registerIndex>118</registerIndex>
          <scale>2</scale>
          <isMean>true</isMean>
          <commandName>cmd_ek5a_${object.index}_3_54_66</commandName>
          <divider>1</divider>
        </lowPropertyDefines>
        <name>Electrial.UcaLine.Voltage</name>
      </Byte4ToFloatComputeSensorDefine>
    </iSensorDefines>
  </DeviceDefine>
</linked-list>