<root>
<#list tsdList as object>
    <deviceActionDefine>
        <deviceId>${object.deviceId}</deviceId>
        <actionDefines>
            <actionDefine>
                <actionName>Fan_PowerOn</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.PowerOn</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_PowerOff</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.PowerOff</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_ElectricHeatingOn</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.HeatingOn</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_ElectricHeatingOff</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.HeatingOff</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_CoolingOn</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.ModelSet.Cooling</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_HeatingOn</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.ModelSet.Heating</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_AutoOn</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.ModelSet.Auto</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_AerationOn</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.ModelSet.Aeration</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_DeHumidificationOn</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.ModelSet.DeHumidification</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_SpeedLevel_Low</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.SpeedLevel.Low</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_SpeedLevel_Middle</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.SpeedLevel.Middle</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_SpeedLevel_High</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.SpeedLevel.High</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_SpeedLevel_Auto</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.SpeedLevel.Auto</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_SleepOn</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.Sleep.On</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
            <actionDefine>
                <actionName>Fan_SleepOff</actionName>
                <actionNodes>
                    <actionNode>
                        <actionId>NewFan.TSD.d${object.index}.Sleep.Off</actionId>
                        <delayAfter>1</delayAfter>
                    </actionNode>
                </actionNodes>
            </actionDefine>
        </actionDefines>
    </deviceActionDefine>
</#list>
</root>
