<linked-list>
<#list tsdList as object>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.PowerOn</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>0</regNum>
        <busId>${object.busId}</busId>
        <do__state>1</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.PowerOff</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>0</regNum>
        <busId>${object.busId}</busId>
        <do__state>0</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.HeatingOn</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>1</regNum>
        <busId>${object.busId}</busId>
        <do__state>0</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.HeatingOff</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>1</regNum>
        <busId>${object.busId}</busId>
        <do__state>0</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.ModelSet.Cooling</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>2</regNum>
        <busId>${object.busId}</busId>
        <do__state>1</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.ModelSet.Heating</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>2</regNum>
        <busId>${object.busId}</busId>
        <do__state>2</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.ModelSet.Auto</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>2</regNum>
        <busId>${object.busId}</busId>
        <do__state>3</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.ModelSet.Aeration</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>2</regNum>
        <busId>${object.busId}</busId>
        <do__state>4</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.ModelSet.DeHumidification</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>2</regNum>
        <busId>${object.busId}</busId>
        <do__state>5</do__state>
    </DoRequest>


    <DoRequest>
        <name>NewFan.TSD.d${object.index}.SpeedLevel.Low</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>4</regNum>
        <busId>${object.busId}</busId>
        <do__state>0</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.SpeedLevel.Middle</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>4</regNum>
        <busId>${object.busId}</busId>
        <do__state>1</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.SpeedLevel.High</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>4</regNum>
        <busId>${object.busId}</busId>
        <do__state>2</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.SpeedLevel.Auto</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>4</regNum>
        <busId>${object.busId}</busId>
        <do__state>3</do__state>
    </DoRequest>

    <DoRequest>
        <name>NewFan.TSD.d${object.index}.Sleep.On</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>5</regNum>
        <busId>${object.busId}</busId>
        <do__state>1</do__state>
    </DoRequest>
    <DoRequest>
        <name>NewFan.TSD.d${object.index}.Sleep.Off</name>
        <commandType>6</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>5</regNum>
        <busId>${object.busId}</busId>
        <do__state>0</do__state>
    </DoRequest>
</#list>
</linked-list>