<linked-list>
<#list tsdList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>NewFan.Power.State</name>
                <registerIndex>0</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_0_6</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Heating.State</name>
                <registerIndex>1</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_0_6</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Model.State</name>
                <registerIndex>2</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_0_6</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Speed.Level</name>
                <registerIndex>4</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_0_6</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Sleep.State</name>
                <registerIndex>5</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_0_6</commandName>
                <divider>1.0</divider>
            </SensorDefine>


            <SwitchSensorDefine>
                <name>NewFan.ElectricHeating.3.State</name>
                <registerIndex>12</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <routeIndex>5</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.ElectricHeating.2.State</name>
                <registerIndex>12</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <routeIndex>4</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.ElectricHeating.1.State</name>
                <registerIndex>12</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <routeIndex>3</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Speed.High.State</name>
                <registerIndex>12</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Speed.Middle.State</name>
                <registerIndex>12</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Speed.Low.State</name>
                <registerIndex>12</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <SensorDefine>
                <name>NewFan.Inner.1.Temperature</name>
                <registerIndex>13</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inner.2.Temperature</name>
                <registerIndex>14</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inner.3.Temperature</name>
                <registerIndex>15</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.ReturnAir.Temperature</name>
                <registerIndex>16</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inner.4.Temperature</name>
                <registerIndex>17</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inner.5.Temperature</name>
                <registerIndex>19</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inner.6.Temperature</name>
                <registerIndex>20</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_12_9</commandName>
                <divider>1.0</divider>
            </SensorDefine>

            <SwitchSensorDefine>
                <name>NewFan.External.1.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_29_5</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Valve.1.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_29_5</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Compressor.1.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_29_5</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <SensorDefine>
                <name>NewFan.Exhaust.1.Temperature</name>
                <registerIndex>30</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_29_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inhale.1.Temperature</name>
                <registerIndex>31</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_29_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Outer.1.Temperature</name>
                <registerIndex>32</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_29_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.1.Temperature</name>
                <registerIndex>33</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_29_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>

            <SwitchSensorDefine>
                <name>NewFan.External.2.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_46_5</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Valve.2.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_46_5</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Compressor.2.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_46_5</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <SensorDefine>
                <name>NewFan.Exhaust.2.Temperature</name>
                <registerIndex>30</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_46_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inhale.2.Temperature</name>
                <registerIndex>31</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_46_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Outer.2.Temperature</name>
                <registerIndex>32</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_46_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.2.Temperature</name>
                <registerIndex>33</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_46_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>

            <SwitchSensorDefine>
                <name>NewFan.External.3.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_63_5</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Valve.3.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_63_5</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Compressor.3.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_63_5</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <SensorDefine>
                <name>NewFan.Exhaust.3.Temperature</name>
                <registerIndex>30</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_63_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inhale.3.Temperature</name>
                <registerIndex>31</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_63_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Outer.3.Temperature</name>
                <registerIndex>32</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_63_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.3.Temperature</name>
                <registerIndex>33</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_63_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>

            <SwitchSensorDefine>
                <name>NewFan.External.4.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_80_5</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Valve.4.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_80_5</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Compressor.4.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_80_5</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <SensorDefine>
                <name>NewFan.Exhaust.4.Temperature</name>
                <registerIndex>30</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_80_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inhale.4.Temperature</name>
                <registerIndex>31</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_80_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Outer.4.Temperature</name>
                <registerIndex>32</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_80_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.4.Temperature</name>
                <registerIndex>33</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_80_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>

            <SwitchSensorDefine>
                <name>NewFan.External.5.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_97_5</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Valve.5.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_97_5</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Compressor.5.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_97_5</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <SensorDefine>
                <name>NewFan.Exhaust.5.Temperature</name>
                <registerIndex>30</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_97_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inhale.5.Temperature</name>
                <registerIndex>31</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_97_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Outer.5.Temperature</name>
                <registerIndex>32</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_97_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.5.Temperature</name>
                <registerIndex>33</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_97_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>

            <SwitchSensorDefine>
                <name>NewFan.External.6.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_114_5</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Valve.6.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_114_5</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>NewFan.Compressor.6.Output.State</name>
                <registerIndex>29</registerIndex>
                <commandName>NewFan_TSD_d${object.index}_AI_114_5</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <SensorDefine>
                <name>NewFan.Exhaust.6.Temperature</name>
                <registerIndex>30</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_114_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Inhale.6.Temperature</name>
                <registerIndex>31</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_114_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.Outer.6.Temperature</name>
                <registerIndex>32</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_114_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>NewFan.6.Temperature</name>
                <registerIndex>33</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>NewFan_TSD_d${object.index}_AI_114_5</commandName>
                <divider>1.0</divider>
            </SensorDefine>

        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>