<linked-list>
<#list pduList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <isState>false</isState>
                <name>Voltage</name>
                <registerIndex>2</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Current</name>
                <registerIndex>3</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1000.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>active_power</name>
                <registerIndex>4</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>reactive_power</name>
                <registerIndex>5</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>inspecting_power</name>
                <registerIndex>6</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>frequency</name>
                <registerIndex>7</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>base_power_factor</name>
                <registerIndex>8</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>all_power_factor</name>
                <registerIndex>9</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Temperature</name>
                <registerIndex>10</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>humidity</name>
                <registerIndex>11</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>out_factory_single</name>
                <registerIndex>12</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>HFCONST.Current.Flag</name>
                <registerIndex>13</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>true</isState>
                <name>default.CF</name>
                <registerIndex>14</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>reactive.power.address.postion</name>
                <registerIndex>15</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Voltage.Effective</name>
                <registerIndex>17</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Current.Effective</name>
                <registerIndex>18</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Active.Power</name>
                <registerIndex>19</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Reactive.Power</name>
                <registerIndex>20</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Inspecting.Power</name>
                <registerIndex>21</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Frenecy</name>
                <registerIndex>22</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Power.Factory</name>
                <registerIndex>23</registerIndex>
                <scale>4</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>false</isState>
                <name>Percentage</name>
                <registerIndex>24</registerIndex>
                <scale>4</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <ComputeSensorDefine>
                <isState>false</isState>
                <highPropertyDefines>
                    <isState>false</isState>
                    <name>Power.Energy.H</name>
                    <registerIndex>25</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                    <divider>1.0</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <isState>false</isState>
                    <name>Power.Energy.L</name>
                    <registerIndex>26</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                    <divider>1.0</divider>
                </lowPropertyDefines>
                <name>Power.Energy</name>
            </ComputeSensorDefine>
            <SensorDefine>
                <isState>true</isState>
                <name>Alert.Value.Setting</name>
                <registerIndex>29</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <isState>true</isState>
                <name>Alert.Flag</name>
                <registerIndex>30</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}</commandName>
                <divider>1.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>