<linked-list>
    <DeviceDefine>
        <deviceId>9FB53904-3D1D-4531-8355-0B046C4CACE4</deviceId>
        <iSensorDefines>
            <SwitchSensorDefine>
                <name>DIOM.DI0</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>0</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI1</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>1</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI2</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>2</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI3</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>3</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI4</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>4</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI5</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>5</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI6</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>6</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI7</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>7</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI8</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>8</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI9</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>9</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI10</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>10</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI11</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>11</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI12</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>12</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI13</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>13</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI14</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>14</routeIndex>
            </SwitchSensorDefine>
            <SwitchSensorDefine>
                <name>DIOM.DI15</name>
                <registerIndex>784</registerIndex>
                <commandName>cmd_r2_diom_thunderPro_d1_QDI</commandName>
                <routeIndex>15</routeIndex>
            </SwitchSensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</linked-list>
