<linked-list>
<#list emhList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId1}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Temperature</name>
                <registerIndex>8</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>9</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
    <DeviceDefine>
        <deviceId>${object.deviceId2}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>10</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>11</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId3}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>16</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>17</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId4}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>18</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>19</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId5}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>24</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>25</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId6}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>26</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>27</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId7}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>32</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>33</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId8}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>34</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>35</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId9}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>40</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>41</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId10}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>42</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>43</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId11}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>48</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>49</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>

    <DeviceDefine>
        <deviceId>${object.deviceId12}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>TH.Tempture</name>
                <registerIndex>50</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>TH.Humidity</name>
                <registerIndex>51</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>Modbus_CAEMH_AI_8_124_d${object.index}</commandName>
                <divider>100.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>

