<linked-list>
<#list elmList as object>
    <ModbusRequest>
        <name>cmd_dtm830c_${object.index}_3_40051_24</name>
        <commandType>3</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <busId>${object.busId}</busId>
        <length>24</length>
        <registerNumber>51</registerNumber>
    </ModbusRequest>
    <ModbusRequest>
        <name>cmd_dtm830c_${object.index}_3_40075_35</name>
        <commandType>3</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <busId>${object.busId}</busId>
        <length>35</length><!--39-->
        <registerNumber>75</registerNumber>
    </ModbusRequest>
    <#--<ModbusRequest>-->
        <#--<name>cmd_dtm830c_${object.index}_3_40111_20</name>-->
        <#--<commandType>3</commandType>-->
        <#--<destinationHost>${object.ip}</destinationHost>-->
        <#--<port>${object.port}</port>-->
        <#--<busId>${object.busId}</busId>-->
        <#--<length>20</length><!--39&ndash;&gt;-->
        <#--<registerNumber>111</registerNumber>-->
    <#--</ModbusRequest>-->
</#list>
</linked-list>