<linked-list>
<#list elmList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>ELM.A.Voltage</name>
                <registerIndex>40051</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.Voltage</name>
                <registerIndex>40052</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.Voltage</name>
                <registerIndex>40053</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.LineVoltage.AB</name>
                <registerIndex>40054</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.LineVoltage.BC</name>
                <registerIndex>40055</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.LineVoltage.CA</name>
                <registerIndex>40056</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.A.Current</name>
                <registerIndex>40057</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.Current</name>
                <registerIndex>40058</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.Current</name>
                <registerIndex>40059</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <ComputeSensorDefine>
                <name>ELM.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.ActivePower_h</name>
                    <registerIndex>40061</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ActivePower_l</name>
                    <registerIndex>40060</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.ReactivePower_h</name>
                    <registerIndex>40063</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ReactivePower_l</name>
                    <registerIndex>40062</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <SensorDefine>
                <name>ELM.PowerFactor</name>
                <registerIndex>40064</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.A.ActivePower</name>
                <registerIndex>40065</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.ActivePower</name>
                <registerIndex>40066</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.ActivePower</name>
                <registerIndex>40067</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.A.ReactivePower</name>
                <registerIndex>40068</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.ReactivePower</name>
                <registerIndex>40069</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.ReactivePower</name>
                <registerIndex>40070</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.A.PowerFactor</name>
                <registerIndex>40071</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.PowerFactor</name>
                <registerIndex>40072</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.PowerFactor</name>
                <registerIndex>40073</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.Frequency</name>
                <registerIndex>40074</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40051_24</commandName>
                <divider>100</divider>
            </SensorDefine>
            <ComputeSensorDefine>
                <name>ELM.ActiveDegree</name>
                <highPropertyDefines>
                    <name>ELM.ActiveDegree_h</name>
                    <registerIndex>40076</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ActiveDegree_l</name>
                    <registerIndex>40075</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.ReactiveDegree</name>
                <highPropertyDefines>
                    <name>ELM.ReactiveDegree_h</name>
                    <registerIndex>40078</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ReactiveDegree_l</name>
                    <registerIndex>40077</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.Input.ActiveDegree</name>
                <highPropertyDefines>
                    <name>ELM.Input.ActiveDegree_h</name>
                    <registerIndex>40080</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Input.ActiveDegree_l</name>
                    <registerIndex>40079</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.Output.ActiveDegree</name>
                <highPropertyDefines>
                    <name>ELM.Output.ActiveDegree_h</name>
                    <registerIndex>40082</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Output.ActiveDegree_l</name>
                    <registerIndex>40081</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.Input.ReactiveDegree</name>
                <highPropertyDefines>
                    <name>ELM.Input.ReactiveDegree_h</name>
                    <registerIndex>40084</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Input.ReactiveDegree_l</name>
                    <registerIndex>40083</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.Output.ReactiveDegree</name>
                <highPropertyDefines>
                    <name>ELM.Output.ReactiveDegree_h</name>
                    <registerIndex>40086</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Output.ReactiveDegree_l</name>
                    <registerIndex>40085</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <SensorDefine>
                <name>ELM.Switch.Status</name>
                <registerIndex>40087</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.Relay.Status</name>
                <registerIndex>40088</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.A.Voltage.THD</name>
                <registerIndex>40089</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.Voltage.THD</name>
                <registerIndex>40090</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.Voltage.THD</name>
                <registerIndex>40091</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.A.Current.THD</name>
                <registerIndex>40092</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.Current.THD</name>
                <registerIndex>40093</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.Current.THD</name>
                <registerIndex>40094</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <!--中线性电流-->
            <SensorDefine>
                <name>ELM.Middle.Current</name>
                <registerIndex>40095</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.Average.Current</name>
                <registerIndex>40096</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.Line.Average.Voltage</name>
                <registerIndex>40097</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.ABC.Average.Voltage</name>
                <registerIndex>40098</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.A.Voltage.Distortion.Rate</name>
                <registerIndex>40099</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.Voltage.Distortion.Rate</name>
                <registerIndex>40100</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.Voltage.Distortion.Rate</name>
                <registerIndex>40101</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.A.Current.Distortion.Rate</name>
                <registerIndex>40102</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.Current.Distortion.Rate</name>
                <registerIndex>40103</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.Current.Distortion.Rate</name>
                <registerIndex>40104</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.A.ApparentPower</name>
                <registerIndex>40106</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.ApparentPower</name>
                <registerIndex>40107</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.ApparentPower</name>
                <registerIndex>40108</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>10</divider>
            </SensorDefine>
            <ComputeSensorDefine>
                <name>ELM.ApparentPower</name>
                <highPropertyDefines>
                    <name>ELM.ApparentPower_h</name>
                    <registerIndex>40110</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.ApparentPower_l</name>
                    <registerIndex>40109</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <SensorDefine>
                <name>ELM.A.Average.Current</name>
                <registerIndex>40111</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.Average.Current</name>
                <registerIndex>40112</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.Average.Current</name>
                <registerIndex>40113</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40075_39</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.Zero.Average.Current</name>
                <registerIndex>40114</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <ComputeSensorDefine>
                <name>ELM.Average.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.Average.ActivePower_h</name>
                    <registerIndex>40116</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Average.ActivePower_l</name>
                    <registerIndex>40115</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.Average.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.Average.ReactivePower_h</name>
                    <registerIndex>40118</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Average.ReactivePower_l</name>
                    <registerIndex>40117</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <SensorDefine>
                <name>ELM.A.Max.Current</name>
                <registerIndex>40121</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.B.Max.Current</name>
                <registerIndex>40122</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.C.Max.Current</name>
                <registerIndex>40123</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ELM.Zero.Max.Current</name>
                <registerIndex>40124</registerIndex>
                <scale>3</scale>
                <isMean>false</isMean>
                <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                <divider>1000</divider>
            </SensorDefine>
            <ComputeSensorDefine>
                <name>ELM.Apparent.Energy</name>
                <highPropertyDefines>
                    <name>ELM.Apparent.Energy_h</name>
                    <registerIndex>40128</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Apparent.Energy_l</name>
                    <registerIndex>40127</registerIndex>
                    <scale>1</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
            <ComputeSensorDefine>
                <name>ELM.Runtime</name>
                <highPropertyDefines>
                    <name>ELM.Runtime_h</name>
                    <registerIndex>40130</registerIndex>
                    <scale>0</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.Runtime_l</name>
                    <registerIndex>40129</registerIndex>
                    <scale>0</scale>
                    <isMean>true</isMean>
                    <commandName>cmd_dtm830c_${object.index}_3_40114_17</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>