<linked-list>
<#list diomList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>DIOM.DO1</name>
                <registerIndex>0</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_1_0_4</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DO2</name>
                <registerIndex>1</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_1_0_4</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DO3</name>
                <registerIndex>2</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_1_0_4</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DO4</name>
                <registerIndex>3</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_1_0_4</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DI1</name>
                <registerIndex>0</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_2_0_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DI2</name>
                <registerIndex>1</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_2_0_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DI3</name>
                <registerIndex>2</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_2_0_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DI4</name>
                <registerIndex>3</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_2_0_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DI5</name>
                <registerIndex>4</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_2_0_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DI6</name>
                <registerIndex>5</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_2_0_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DI7</name>
                <registerIndex>6</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_2_0_8</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>DIOM.DI8</name>
                <registerIndex>7</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_bcu301_${object.index}_2_0_8</commandName>
                <divider>1</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
