<linked-list>
<#list elmList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <!-- 第一路 -->
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.A.Current</name>
                <highPropertyDefines>
                    <name>ELM.1.A.Current_h</name>
                    <registerIndex>2999</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.A.Current_l</name>
                    <registerIndex>3000</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.B.Current</name>
                <highPropertyDefines>
                    <name>ELM.1.B.Current_h</name>
                    <registerIndex>3001</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.B.Current_l</name>
                    <registerIndex>3002</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.C.Current</name>
                <highPropertyDefines>
                    <name>ELM.1.C.Current_h</name>
                    <registerIndex>3003</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.C.Current_l</name>
                    <registerIndex>3004</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.LineVoltage.AB</name>
                <highPropertyDefines>
                    <name>ELM.1.LineVoltage_AB_h</name>
                    <registerIndex>3019</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.LineVoltage_AB_l</name>
                    <registerIndex>3020</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.LineVoltage.BC</name>
                <highPropertyDefines>
                    <name>ELM.1.LineVoltage_BC_h</name>
                    <registerIndex>3021</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.LineVoltage_BC_l</name>
                    <registerIndex>3022</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.LineVoltage.CA</name>
                <highPropertyDefines>
                    <name>ELM.1.LineVoltage_CA_h</name>
                    <registerIndex>3023</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.LineVoltage_CA_l</name>
                    <registerIndex>3024</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.A.Voltage</name>
                <highPropertyDefines>
                    <name>ELM.1.A.Voltage_h</name>
                    <registerIndex>3027</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.A.Voltage_l</name>
                    <registerIndex>3028</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.B.Voltage</name>
                <highPropertyDefines>
                    <name>ELM.1.B.Voltage_h</name>
                    <registerIndex>3029</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.B.Voltage_l</name>
                    <registerIndex>3030</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.C.Voltage</name>
                <highPropertyDefines>
                    <name>ELM.1.C.Voltage_h</name>
                    <registerIndex>3031</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.C.Voltage_l</name>
                    <registerIndex>3032</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.A.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.1.A.ActivePower_h</name>
                    <registerIndex>3053</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.A.ActivePower_l</name>
                    <registerIndex>3054</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.B.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.1.B.ActivePower_h</name>
                    <registerIndex>3055</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.B.ActivePower_l</name>
                    <registerIndex>3056</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.C.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.1.C.ActivePower_h</name>
                    <registerIndex>3057</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.C.ActivePower_l</name>
                    <registerIndex>3058</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.1.ActivePower_h</name>
                    <registerIndex>3059</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.ActivePower_l</name>
                    <registerIndex>3060</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.A.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.1.A.ReactivePower_h</name>
                    <registerIndex>3061</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.A.ReactivePower_l</name>
                    <registerIndex>3062</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.B.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.1.B.ReactivePower_h</name>
                    <registerIndex>3063</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.B.ReactivePower_l</name>
                    <registerIndex>3064</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.C.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.1.C.ReactivePower_h</name>
                    <registerIndex>3065</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.C.ReactivePower_l</name>
                    <registerIndex>3066</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.1.ReactivePower_h</name>
                    <registerIndex>3067</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.ReactivePower_l</name>
                    <registerIndex>3068</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.A.ApparentPower</name>
                <highPropertyDefines>
                    <name>ELM.1.A.ApparentPower_h</name>
                    <registerIndex>3069</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.A.ApparentPower_l</name>
                    <registerIndex>3070</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.B.ApparentPower</name>
                <highPropertyDefines>
                    <name>ELM.1.B.ApparentPower_h</name>
                    <registerIndex>3071</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.B.ApparentPower_l</name>
                    <registerIndex>3072</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.C.ApparentPower</name>
                <highPropertyDefines>
                    <name>ELM.1.C.ApparentPower_h</name>
                    <registerIndex>3073</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.C.ApparentPower_l</name>
                    <registerIndex>3074</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.ApparentPower</name>
                <highPropertyDefines>
                    <name>ELM.1.ApparentPower_h</name>
                    <registerIndex>3076</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.ApparentPower_l</name>
                    <registerIndex>3076</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>


            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.A.PowerFactor</name>
                <highPropertyDefines>
                    <name>ELM.1.A.PowerFactor_h</name>
                    <registerIndex>3077</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.A.PowerFactor_l</name>
                    <registerIndex>3078</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.B.PowerFactor</name>
                <highPropertyDefines>
                    <name>ELM.1.B.PowerFactor_h</name>
                    <registerIndex>3079</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.B.PowerFactor_l</name>
                    <registerIndex>3080</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.C.PowerFactor</name>
                <highPropertyDefines>
                    <name>ELM.1.C.PowerFactor_h</name>
                    <registerIndex>3081</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.C.PowerFactor_l</name>
                    <registerIndex>3082</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.PowerFactor</name>
                <highPropertyDefines>
                    <name>ELM.1.PowerFactor_h</name>
                    <registerIndex>3083</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.PowerFactor_l</name>
                    <registerIndex>3084</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.1.Frequency</name>
                <highPropertyDefines>
                    <name>ELM.1.Frequency_h</name>
                    <registerIndex>3109</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.1.Frequency_l</name>
                    <registerIndex>3110</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_1_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <!-- 第二路 -->
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.A.Current</name>
                <highPropertyDefines>
                    <name>ELM.2.A.Current_h</name>
                    <registerIndex>2999</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.A.Current_l</name>
                    <registerIndex>3000</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.B.Current</name>
                <highPropertyDefines>
                    <name>ELM.2.B.Current_h</name>
                    <registerIndex>3001</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.B.Current_l</name>
                    <registerIndex>3002</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.C.Current</name>
                <highPropertyDefines>
                    <name>ELM.2.C.Current_h</name>
                    <registerIndex>3003</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.C.Current_l</name>
                    <registerIndex>3004</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.LineVoltage.AB</name>
                <highPropertyDefines>
                    <name>ELM.2.LineVoltage_AB_h</name>
                    <registerIndex>3019</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.LineVoltage_AB_l</name>
                    <registerIndex>3020</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.LineVoltage.BC</name>
                <highPropertyDefines>
                    <name>ELM.2.LineVoltage_BC_h</name>
                    <registerIndex>3021</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.LineVoltage_BC_l</name>
                    <registerIndex>3022</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.LineVoltage.CA</name>
                <highPropertyDefines>
                    <name>ELM.2.LineVoltage_CA_h</name>
                    <registerIndex>3023</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.LineVoltage_CA_l</name>
                    <registerIndex>3024</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.A.Voltage</name>
                <highPropertyDefines>
                    <name>ELM.2.A.Voltage_h</name>
                    <registerIndex>3027</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.A.Voltage_l</name>
                    <registerIndex>3028</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.B.Voltage</name>
                <highPropertyDefines>
                    <name>ELM.2.B.Voltage_h</name>
                    <registerIndex>3029</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.B.Voltage_l</name>
                    <registerIndex>3030</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.C.Voltage</name>
                <highPropertyDefines>
                    <name>ELM.2.C.Voltage_h</name>
                    <registerIndex>3031</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.C.Voltage_l</name>
                    <registerIndex>3032</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.A.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.2.A.ActivePower_h</name>
                    <registerIndex>3053</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.A.ActivePower_l</name>
                    <registerIndex>3054</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.B.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.2.B.ActivePower_h</name>
                    <registerIndex>3055</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.B.ActivePower_l</name>
                    <registerIndex>3056</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.C.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.2.C.ActivePower_h</name>
                    <registerIndex>3057</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.C.ActivePower_l</name>
                    <registerIndex>3058</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.ActivePower</name>
                <highPropertyDefines>
                    <name>ELM.2.ActivePower_h</name>
                    <registerIndex>3059</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.ActivePower_l</name>
                    <registerIndex>3060</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.A.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.2.A.ReactivePower_h</name>
                    <registerIndex>3061</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.A.ReactivePower_l</name>
                    <registerIndex>3062</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.B.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.2.B.ReactivePower_h</name>
                    <registerIndex>3063</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.B.ReactivePower_l</name>
                    <registerIndex>3064</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.C.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.2.C.ReactivePower_h</name>
                    <registerIndex>3065</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.C.ReactivePower_l</name>
                    <registerIndex>3066</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.ReactivePower</name>
                <highPropertyDefines>
                    <name>ELM.2.ReactivePower_h</name>
                    <registerIndex>3067</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.ReactivePower_l</name>
                    <registerIndex>3068</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.A.ApparentPower</name>
                <highPropertyDefines>
                    <name>ELM.2.A.ApparentPower_h</name>
                    <registerIndex>3069</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.A.ApparentPower_l</name>
                    <registerIndex>3070</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.B.ApparentPower</name>
                <highPropertyDefines>
                    <name>ELM.2.B.ApparentPower_h</name>
                    <registerIndex>3071</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.B.ApparentPower_l</name>
                    <registerIndex>3072</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.C.ApparentPower</name>
                <highPropertyDefines>
                    <name>ELM.2.C.ApparentPower_h</name>
                    <registerIndex>3073</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.C.ApparentPower_l</name>
                    <registerIndex>3074</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.ApparentPower</name>
                <highPropertyDefines>
                    <name>ELM.2.ApparentPower_h</name>
                    <registerIndex>3076</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.ApparentPower_l</name>
                    <registerIndex>3076</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>


            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.A.PowerFactor</name>
                <highPropertyDefines>
                    <name>ELM.2.A.PowerFactor_h</name>
                    <registerIndex>3077</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.A.PowerFactor_l</name>
                    <registerIndex>3078</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.B.PowerFactor</name>
                <highPropertyDefines>
                    <name>ELM.2.B.PowerFactor_h</name>
                    <registerIndex>3079</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.B.PowerFactor_l</name>
                    <registerIndex>3080</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.C.PowerFactor</name>
                <highPropertyDefines>
                    <name>ELM.2.C.PowerFactor_h</name>
                    <registerIndex>3081</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.C.PowerFactor_l</name>
                    <registerIndex>3082</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.PowerFactor</name>
                <highPropertyDefines>
                    <name>ELM.2.PowerFactor_h</name>
                    <registerIndex>3083</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.PowerFactor_l</name>
                    <registerIndex>3084</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>ELM.2.Frequency</name>
                <highPropertyDefines>
                    <name>ELM.2.Frequency_h</name>
                    <registerIndex>3109</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>ELM.2.Frequency_l</name>
                    <registerIndex>3110</registerIndex>
                    <scale>2</scale>
                    <isMean>false</isMean>
                    <commandName>cmd_pm5350bw_2_${object.index}_3_3000_111</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
