<linked-list>
<#list pduList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.1.Voltage</name>
                <highPropertyDefines>
                    <name>PDU.1.MainSupply.Voltage.H</name>
                    <registerIndex>0</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.1.MainSupply.Voltage.L</name>
                    <registerIndex>1</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.1.Current</name>
                <highPropertyDefines>
                    <name>PDU.1.MainSupply.Current.H</name>
                    <registerIndex>2</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.1.MainSupply.Current.L</name>
                    <registerIndex>3</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.1.ActivePower</name>
                <highPropertyDefines>
                    <name>PDU.1.ActivePower.H</name>
                    <registerIndex>6</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.1.ActivePower.L</name>
                    <registerIndex>7</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.1.Humidity</name>
                <highPropertyDefines>
                    <name>PDU.1.Humidity.H</name>
                    <registerIndex>14</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.1.Humidity.L</name>
                    <registerIndex>15</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.1.Temperature</name>
                <highPropertyDefines>
                    <name>PDU.1.Temperature.H</name>
                    <registerIndex>16</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.1.Temperature.L</name>
                    <registerIndex>17</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.1.ActiveEnergy</name>
                <highPropertyDefines>
                    <name>PDU.1.ElectricQuantity.H</name>
                    <registerIndex>18</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.1.ElectricQuantity.L</name>
                    <registerIndex>19</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_A_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.2.Voltage</name>
                <highPropertyDefines>
                    <name>PDU.2.MainSupply.Voltage.H</name>
                    <registerIndex>0</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.2.MainSupply.Voltage.L</name>
                    <registerIndex>1</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.2.Current</name>
                <highPropertyDefines>
                    <name>PDU.2.MainSupply.Current.H</name>
                    <registerIndex>2</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.2.MainSupply.Current.L</name>
                    <registerIndex>3</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.2.ActivePower</name>
                <highPropertyDefines>
                    <name>PDU.2.ActivePower.H</name>
                    <registerIndex>6</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.2.ActivePower.L</name>
                    <registerIndex>7</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.2.Humidity</name>
                <highPropertyDefines>
                    <name>PDU.2.Humidity.H</name>
                    <registerIndex>14</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.2.Humidity.L</name>
                    <registerIndex>15</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.2.Temperature</name>
                <highPropertyDefines>
                    <name>PDU.2.Temperature.H</name>
                    <registerIndex>16</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.2.Temperature.L</name>
                    <registerIndex>17</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>
            <Byte4ToFloatComputeSensorDefine>
                <name>PDU.2.ActiveEnergy</name>
                <highPropertyDefines>
                    <name>PDU.2.ElectricQuantity.H</name>
                    <registerIndex>18</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>PDU.2.ElectricQuantity.L</name>
                    <registerIndex>19</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_spem_B_${object.index}_3_0_30</commandName>
                    <divider>1</divider>
                </lowPropertyDefines>
            </Byte4ToFloatComputeSensorDefine>

            <SensorDefine>
                <name>THADA.1.Temperature</name>
                <registerIndex>8</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.1.Humidity</name>
                <registerIndex>9</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.2.Temperature</name>
                <registerIndex>10</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.2.Humidity</name>
                <registerIndex>11</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.3.Temperature</name>
                <registerIndex>12</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.3.Humidity</name>
                <registerIndex>13</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.4.Temperature</name>
                <registerIndex>14</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.4.Humidity</name>
                <registerIndex>15</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.5.Temperature</name>
                <registerIndex>16</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.5.Humidity</name>
                <registerIndex>17</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.6.Temperature</name>
                <registerIndex>18</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.6.Humidity</name>
                <registerIndex>19</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>th_thada_d${object.index}_3_9_12</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.State.Magnetometer</name>
                <registerIndex>14</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>th_thada_d${object.index}_3_14_7</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.Alert.T.1.Over</name>
                <registerIndex>15</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>th_thada_d${object.index}_3_14_7</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.Alert.T.2.Over</name>
                <registerIndex>16</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>th_thada_d${object.index}_3_14_7</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.Alert.T.3.Over</name>
                <registerIndex>17</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>th_thada_d${object.index}_3_14_7</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.Alert.T.4.Over</name>
                <registerIndex>18</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>th_thada_d${object.index}_3_14_7</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.Alert.T.5.Over</name>
                <registerIndex>19</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>th_thada_d${object.index}_3_14_7</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>THADA.Alert.T.6.Over</name>
                <registerIndex>20</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>th_thada_d${object.index}_3_14_7</commandName>
                <divider>1.0</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>