<linked-list>
<#list pduList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.Voltage</name>
                <registerIndex>2</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_1</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.Current</name>
                <registerIndex>3</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_1</commandName>
                <divider>1000.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.ActivePower</name>
                <registerIndex>4</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_1</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.Temperature</name>
                <registerIndex>10</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_1</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.1.Humidity</name>
                <registerIndex>11</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_1</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <ComputeSensorDefine>
                <name>RACK.BackDoor.PDU.1.ActiveEnergy</name>
                <highPropertyDefines>
                    <name>Power.Energy.H</name>
                    <registerIndex>25</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_v2_AI_0_31_d${object.index}_1</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>Power.Energy.L</name>
                    <registerIndex>26</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_v2_AI_0_31_d${object.index}_1</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>

            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.Voltage</name>
                <registerIndex>2</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_2</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.Current</name>
                <registerIndex>3</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_2</commandName>
                <divider>1000.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.ActivePower</name>
                <registerIndex>4</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_2</commandName>
                <divider>1.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.Temperature</name>
                <registerIndex>10</registerIndex>
                <scale>2</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_2</commandName>
                <divider>100.0</divider>
            </SensorDefine>
            <SensorDefine>
                <name>RACK.BackDoor.PDU.2.Humidity</name>
                <registerIndex>11</registerIndex>
                <scale>1</scale>
                <isMean>false</isMean>
                <commandName>pdu_v2_AI_0_31_d${object.index}_2</commandName>
                <divider>10.0</divider>
            </SensorDefine>
            <ComputeSensorDefine>
                <name>RACK.BackDoor.PDU.2.ActiveEnergy</name>
                <highPropertyDefines>
                    <name>Power.Energy.H</name>
                    <registerIndex>25</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_v2_AI_0_31_d${object.index}_2</commandName>
                    <divider>10</divider>
                </highPropertyDefines>
                <lowPropertyDefines>
                    <name>Power.Energy.L</name>
                    <registerIndex>26</registerIndex>
                    <scale>2</scale>
                    <isMean>true</isMean>
                    <commandName>pdu_v2_AI_0_31_d${object.index}_2</commandName>
                    <divider>10</divider>
                </lowPropertyDefines>
            </ComputeSensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>