<linked-list>
<#list upsList as object>
  <DeviceDefine>
    <deviceId>${object.deviceId}</deviceId>
    <iSensorDefines>
        <SwitchSensorDefine>
            <name>UPS.LoadProtected.Status</name>
            <registerIndex>64</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>0</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Coupled.Status</name>
            <registerIndex>64</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>1</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Unit</name>
            <registerIndex>64</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>2</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.System.Downgraded.Operation</name>
            <registerIndex>64</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>3</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Backup.Switch.Status</name>
            <registerIndex>64</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>4</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Battery.low</name>
            <registerIndex>64</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>5</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Emergency.Stop.Status</name>
            <registerIndex>64</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>11</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mode.OnLine.Status</name>
            <registerIndex>65</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>1</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mode.Eco.Status</name>
            <registerIndex>65</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>2</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Bypass.Switch.Status</name>
            <registerIndex>65</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>6</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Battery.Maintain</name>
            <registerIndex>66</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>1</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Battery.TestResult.Status</name>
            <registerIndex>66</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>2</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Battery.Testing.Status</name>
            <registerIndex>66</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>8</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Battery.Temperature.Over</name>
            <registerIndex>66</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>10</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Battery.CircuitBreaker.Switch.Status</name>
            <registerIndex>66</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>15</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mains.1.Input.Switch.Status</name>
            <registerIndex>68</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>3</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mains.1.Voltage.Over</name>
            <registerIndex>68</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>8</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mains.1.Fuse.Fault</name>
            <registerIndex>68</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>9</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mains.1.Frequency.Over</name>
            <registerIndex>68</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>11</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.RectifierThermal.Overload</name>
            <registerIndex>68</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>12</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mains.2.Overload</name>
            <registerIndex>70</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>5</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mains.2.Thermal.Overload</name>
            <registerIndex>70</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>6</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Bypass.VoltageOrFrequency.Over</name>
            <registerIndex>70</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>7</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mains.2.Voltage.Over</name>
            <registerIndex>70</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>10</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.M2.Over</name>
            <registerIndex>70</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>11</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Mains.2.Input.Switch.Status</name>
            <registerIndex>70</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>14</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Output.Switch.Status</name>
            <registerIndex>71</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>11</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.ChargerGeneral.Fault</name>
            <registerIndex>73</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>0</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Battery.Charged.Status</name>
            <registerIndex>73</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>3</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Major.Fault</name>
            <registerIndex>76</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>1</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Inverter.Overload</name>
            <registerIndex>76</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>2</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Inverter.Thermal.Overload</name>
            <registerIndex>76</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>3</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Inverter.Limitation.Status</name>
            <registerIndex>76</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>4</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Inverter.Fuse.Fault</name>
            <registerIndex>76</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>5</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Output.Thermal.Overload</name>
            <registerIndex>77</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>15</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Alarm.Output.Overload</name>
            <registerIndex>79</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>0</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Output.ShortCircuit.Status</name>
            <registerIndex>79</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>1</routeIndex>
        </SwitchSensorDefine>
        <SwitchSensorDefine>
            <name>UPS.Warrant.End</name>
            <registerIndex>67</registerIndex>
            <commandName>cmd_galaxy5500_${object.index}_3_64_16</commandName>
            <routeIndex>1</routeIndex>
        </SwitchSensorDefine>
        <SensorDefine>
            <name>UPS.Mains.1.I1.Current</name>
            <registerIndex>256</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.1.I2.Current</name>
            <registerIndex>257</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.1.I3.Current</name>
            <registerIndex>258</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.2.I1.Current</name>
            <registerIndex>262</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.2.I2.Current</name>
            <registerIndex>263</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.2.I3.Current</name>
            <registerIndex>264</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.I1.Current</name>
            <registerIndex>265</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.I2.Current</name>
            <registerIndex>266</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.I3.Current</name>
            <registerIndex>267</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Battery.Current</name>
            <registerIndex>270</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.1.U12.Voltage</name>
            <registerIndex>277</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.1.U23.Voltage</name>
            <registerIndex>278</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.1.U31.Voltage</name>
            <registerIndex>279</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Inverter.U1N.Voltage</name>
            <registerIndex>280</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Inverter.U2N.Voltage</name>
            <registerIndex>281</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Inverter.U3N.Voltage</name>
            <registerIndex>282</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.2.U12.Voltage</name>
            <registerIndex>289</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.2.U23.Voltage</name>
            <registerIndex>290</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.2.U31.Voltage</name>
            <registerIndex>291</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.U1N.Voltage</name>
            <registerIndex>292</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.U2N.Voltage</name>
            <registerIndex>293</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.U3N.Voltage</name>
            <registerIndex>294</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.U12.Voltage</name>
            <registerIndex>295</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.U23.Voltage</name>
            <registerIndex>296</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.U31.Voltage</name>
            <registerIndex>297</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Battery.Voltage</name>
            <registerIndex>301</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.1.ActivePower</name>
            <registerIndex>304</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.2.ActivePower</name>
            <registerIndex>305</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.3.ActivePower</name>
            <registerIndex>306</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.1.ApparentPower</name>
            <registerIndex>307</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.2.ApparentPower</name>
            <registerIndex>308</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.3.ApparentPower</name>
            <registerIndex>309</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.ActivePower</name>
            <registerIndex>310</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.ApparentPower</name>
            <registerIndex>311</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.LoadRate</name>
            <registerIndex>313</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.1.PowerFactor</name>
            <registerIndex>314</registerIndex>
            <scale>2</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>100</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.2.PowerFactor</name>
            <registerIndex>315</registerIndex>
            <scale>2</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>100</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.3.PowerFactor</name>
            <registerIndex>316</registerIndex>
            <scale>2</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>100</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.PowerFactor</name>
            <registerIndex>317</registerIndex>
            <scale>2</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>100</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.1.Frequency</name>
            <registerIndex>318</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Inverter.Frequency</name>
            <registerIndex>319</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Mains.2.Frequency</name>
            <registerIndex>320</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Output.Frequency</name>
            <registerIndex>321</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Battery.Backup.Time</name>
            <registerIndex>329</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Battery.Temperature</name>
            <registerIndex>330</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Battery.ChargingRate</name>
            <registerIndex>331</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
        <SensorDefine>
            <name>UPS.Battery.RechargeDuration.Time</name>
            <registerIndex>335</registerIndex>
            <scale>0</scale>
            <isMean>false</isMean>
            <commandName>cmd_galaxy5500_${object.index}_3_256_80</commandName>
            <divider>1</divider>
        </SensorDefine>
    </iSensorDefines>
  </DeviceDefine>
</#list>
</linked-list>