<?xml version="1.0" encoding="utf-8" standalone="no"?>
<linked-list>
<#list unityList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>CRAC.Fan.Speed</name>
                <registerIndex>30103</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.FreeCooling.OpenPosition</name>
                <registerIndex>30105</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Reheat.Utilization</name>
                <registerIndex>30106</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Humidifier.Utilization</name>
                <registerIndex>30107</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Dehumidifier.Utilization</name>
                <registerIndex>30108</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.FreeCooling.Status</name>
                <registerIndex>30109</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ReturnAir.Temperature</name>
                <registerIndex>30110</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.SupplyAir.Temperature</name>
                <registerIndex>30112</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.FreeCooling.FluidTemperature</name>
                <registerIndex>30115</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.A.Temperature</name>
                <registerIndex>30116</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.B.Temperature</name>
                <registerIndex>30117</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.C.Temperature</name>
                <registerIndex>30118</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.DigScrollComp.1.Discharge.Temperature</name>
                <registerIndex>30119</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.DigScrollComp.2.Discharge.Temperature</name>
                <registerIndex>30120</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q1_d${object.index}_AI_30103_17</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ReturnAir.Humidity</name>
                <registerIndex>30130</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.A.Humidity</name>
                <registerIndex>30132</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.B.Humidity</name>
                <registerIndex>30133</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>10</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirSensor.C.Humidity</name>
                <registerIndex>30134</registerIndex>
                <scale>1</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>10</divider>
            </SensorDefine>
            <!-- 风机运行时间 小时-->
            <SensorDefine>
                <name>CRAC.Fan.RunningTime</name>
                <registerIndex>30141</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 压缩机运行时间 小时-->
            <SensorDefine>
                <name>CRAC.Compressor.1.RunningTime</name>
                <registerIndex>30142</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 压缩机运行时间 小时-->
            <SensorDefine>
                <name>CRAC.Compressor.2.RunningTime</name>
                <registerIndex>30143</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 加湿器运行 时间 -->
            <SensorDefine>
                <name>CRAC.Humidifier.RunningTime</name>
                <registerIndex>30144</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 除湿器运行 时间 -->
            <SensorDefine>
                <name>CRAC.Dehumidifier.RunningTime</name>
                <registerIndex>30145</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 自然冷却运行 时间 -->
            <SensorDefine>
                <name>CRAC.FreeCooling.RunningTime</name>
                <registerIndex>30146</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 电加热运行 时间 -->
            <SensorDefine>
                <name>CRAC.ElectricReheater.1.RunningTime</name>
                <registerIndex>30147</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ElectricReheater.2.RunningTime</name>
                <registerIndex>30148</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ElectricReheater.3.RunningTime</name>
                <registerIndex>30149</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.HotWaterAndGas.RunningTime</name>
                <registerIndex>30150</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q2_d${object.index}_AI_30130_20</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <name>CRAC.Compressor.1.State</name>
                <registerIndex>30269</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q3_d${object.index}_AI_30269_16</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.State</name>
                <registerIndex>30270</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q3_d${object.index}_AI_30269_16</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.InfraredHumidifier.FlushRate</name>
                <registerIndex>30273</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q3_d${object.index}_AI_30269_16</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.System.Status</name>
                <registerIndex>30279</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q3_d${object.index}_AI_30269_16</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.System.ControlMode</name>
                <registerIndex>30280</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q3_d${object.index}_AI_30269_16</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.HotWaterAndGas.OpenPosition</name>
                <registerIndex>30285</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q3_d${object.index}_AI_30269_16</commandName>
                <divider>1</divider>
            </SensorDefine>

            <!-- 室外温度 -->
            <SensorDefine>
                <name>CRAC.Outside.Temperature</name>
                <registerIndex>30484</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q4_d${object.index}_AI_30484_9</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 压缩机锁定 -->
            <SensorDefine>
                <name>CRAC.Compressor.Lockout</name>
                <registerIndex>30489</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q4_d${object.index}_AI_30484_9</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 加热器锁定 -->
            <SensorDefine>
                <name>CRAC.Reheater.Lockout</name>
                <registerIndex>30492</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q4_d${object.index}_AI_30484_9</commandName>
                <divider>1</divider>
            </SensorDefine>
            <!-- 加湿器锁定 -->
            <SensorDefine>
                <name>CRAC.Humidifier.Lockout</name>
                <registerIndex>30493</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q4_d${object.index}_AI_30484_9</commandName>
                <divider>1</divider>
            </SensorDefine>

            <SensorDefine>
                <name>CRAC.ExtReheat.Lockout</name>
                <registerIndex>10009</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ExtHumidifier.Lockout</name>
                <registerIndex>10010</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ExtCompressor.Lockout</name>
                <registerIndex>10021</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Fan.State</name>
                <registerIndex>10025</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Cooling.State</name>
                <registerIndex>10026</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.FreeCooling.State</name>
                <registerIndex>10027</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.HotWaterAndGas.State</name>
                <registerIndex>10028</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.ElectricReheat.State</name>
                <registerIndex>10029</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Humidifier.State</name>
                <registerIndex>10030</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Dehumidifier.State</name>
                <registerIndex>10031</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Fan.Overload</name>
                <registerIndex>10034</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.AirFlow.Loss</name>
                <registerIndex>10035</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Ext.AirFlow.Loss</name>
                <registerIndex>10036</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.1.Pressure.High</name>
                <registerIndex>10037</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.1.Pressure.Low</name>
                <registerIndex>10038</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.1.Thermal.Overload</name>
                <registerIndex>10039</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.1.Issue</name>
                <registerIndex>10040</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.Pressure.High</name>
                <registerIndex>10041</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.Pressure.Low</name>
                <registerIndex>10042</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.Thermal.Overload</name>
                <registerIndex>10043</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.Issue</name>
                <registerIndex>10044</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Compressor.2.Issue</name>
                <registerIndex>10044</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Smoke</name>
                <registerIndex>10047</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Water</name>
                <registerIndex>10048</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Humidifier.Issue</name>
                <registerIndex>10049</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Return.AirSensor.Issue</name>
                <registerIndex>10053</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Ext.AirBlower.Loss</name>
                <registerIndex>10055</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Humidifier.Water.Low</name>
                <registerIndex>10058</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Humidifier.Current.Over</name>
                <registerIndex>10059</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Ext.Temperature.Over</name>
                <registerIndex>10060</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Ext.Temperature.Over</name>
                <registerIndex>10060</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ReturnAir.Temperature.Over</name>
                <registerIndex>10067</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ReturnAir.Temperature.Under</name>
                <registerIndex>10068</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ReturnAir.Humidity.High</name>
                <registerIndex>10069</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ReturnAir.Humidity.Low</name>
                <registerIndex>10070</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.AirFilter.Clogged</name>
                <registerIndex>10076</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Fan.OverTime</name>
                <registerIndex>10080</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Compressor.1.OverTime</name>
                <registerIndex>10081</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Compressor.2.OverTime</name>
                <registerIndex>10082</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>

            <!--482,10050(1), Ext Standby Glycol Pump On-->
            <!--483,10051(1), Ext Standby Unit On-->
            <!--484,10052(1), Ext Condenser Pump High Water-->
            <!--491,10065(1), Supply Chilled Water Over Temp-->

            <SensorDefine>
                <name>CRAC.Alarm.FreeCooling.OverTime</name>
                <registerIndex>10083</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ElectricReheater.1.OverTime</name>
                <registerIndex>10084</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ElectricReheater.2.OverTime</name>
                <registerIndex>10085</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.ElectricReheater.3.OverTime</name>
                <registerIndex>10086</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.HotWaterAndGas.OverTime</name>
                <registerIndex>10087</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Humidifier.OverTime</name>
                <registerIndex>10088</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Dehumidifier.OverTime</name>
                <registerIndex>10089</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.UnitCommunication.Lost</name>
                <registerIndex>10091</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.MasterUnitCommunication.Lost</name>
                <registerIndex>10092</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.SupplyAir.Temperature.Over</name>
                <registerIndex>10209</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.SupplyAir.Temperature.Under</name>
                <registerIndex>10210</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.AmbientAirSensor.Issue</name>
                <registerIndex>10211</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Ext.FreeCooling.Lockout</name>
                <registerIndex>10214</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Reheater.Temperature.Over</name>
                <registerIndex>10215</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.HumidifierCurrent.Under</name>
                <registerIndex>10217</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Fan.Issue</name>
                <registerIndex>10218</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.CondenserTVSS.Issue</name>
                <registerIndex>10219</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.CondenserVFD.Issue</name>
                <registerIndex>10220</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Condenser.1.Issue</name>
                <registerIndex>10221</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Condenser.2.Issue</name>
                <registerIndex>10222</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.WaterFloorSensor.Issue</name>
                <registerIndex>10228</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>CRAC.Alarm.Fire</name>
                <registerIndex>10229</registerIndex>
                <scale>0</scale>
                <isMean>true</isMean>
                <commandName>crac_unity_q5_d${object.index}_AI_10009_220</commandName>
                <divider>1</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>