<linked-list>
<#list channelList as object>
    <DoRequest>
        <name>cd${object.index}.Electromagnet.1.PowerOn</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>8</regNum>
        <busId>${object.busId}</busId>
        <do__state>1</do__state>
    </DoRequest>
    <DoRequest>
        <name>cd${object.index}.Electromagnet.1.PowerOff</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>8</regNum>
        <busId>${object.busId}</busId>
        <do__state>2</do__state>
    </DoRequest>
    <DoRequest>
        <name>cd${object.index}.Electromagnet.2.PowerOn</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>9</regNum>
        <busId>${object.busId}</busId>
        <do__state>1</do__state>
    </DoRequest>
    <DoRequest>
        <name>cd${object.index}.Electromagnet.2.PowerOff</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>9</regNum>
        <busId>${object.busId}</busId>
        <do__state>2</do__state>
    </DoRequest>
    <DoRequest>
        <name>cd${object.index}.Electromagnet.3.PowerOn</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>10</regNum>
        <busId>${object.busId}</busId>
        <do__state>1</do__state>
    </DoRequest>
    <DoRequest>
        <name>cd${object.index}.Electromagnet.3.PowerOff</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>10</regNum>
        <busId>${object.busId}</busId>
        <do__state>2</do__state>
    </DoRequest>
    <DoRequest>
        <name>cd${object.index}.Pushrod.Push</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>26</regNum>
        <busId>${object.busId}</busId>
        <do__state>1</do__state>
    </DoRequest>
    <DoRequest>
        <name>cd${object.index}.Pushrod.PushReset</name>
        <commandType>5</commandType>
        <destinationHost>${object.ip}</destinationHost>
        <port>${object.port}</port>
        <regNum>26</regNum>
        <busId>${object.busId}</busId>
        <do__state>2</do__state>
    </DoRequest>
</#list>
</linked-list>