<linked-list>
<#list channelList as object>
    <DeviceDefine>
        <deviceId>${object.deviceId}</deviceId>
        <iSensorDefines>
            <SensorDefine>
                <name>ColdChannel.Skylight.Switch.OC</name>
                <registerIndex>11</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.FrontSmoke.Switch.OC</name>
                <registerIndex>12</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.BackSmoke.Switch.OC</name>
                <registerIndex>19</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.Alarm.UrgentPressStop</name>
                <registerIndex>119</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.Alarm.Temperature.High</name>
                <registerIndex>123</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.Alarm.Temperature.Low</name>
                <registerIndex>124</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.Alarm.Humidity.High</name>
                <registerIndex>125</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.Alarm.Humidity.Low</name>
                <registerIndex>126</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.FireControl.InputSignal.OpenAlways</name>
                <registerIndex>120</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.FireControl.InputSignal.CloseAlways</name>
                <registerIndex>121</registerIndex>
                <scale>0</scale>
                <isMean>false</isMean>
                <commandName>cmd_channel${object.index}_1_8_186</commandName>
                <divider>1</divider>
            </SensorDefine>
          
            <SensorDefine>
                <name>ColdChannel.FrontDoor.Temperature</name>
                <registerIndex>8</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>cmd_channel${object.index}_3_8_34</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.FrontDoor.Humidity</name>
                <registerIndex>9</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>cmd_channel${object.index}_3_8_34</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.BackDoor.Temperature</name>
                <registerIndex>10</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>cmd_channel${object.index}_3_8_34</commandName>
                <divider>100</divider>
            </SensorDefine>
            <SensorDefine>
                <name>ColdChannel.BackDoor.Humidity</name>
                <registerIndex>11</registerIndex>
                <scale>2</scale>
                <isMean>true</isMean>
                <commandName>cmd_channel${object.index}_3_8_34</commandName>
                <divider>100</divider>
            </SensorDefine>
        </iSensorDefines>
    </DeviceDefine>
</#list>
</linked-list>
